// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shift_line_buffer_array_ap_ufixed_1u_config2_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_lv1_1 = "1";
const sc_lv<5> shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_lv5_1B = "11011";
const bool shift_line_buffer_array_ap_ufixed_1u_config2_s::ap_const_boolean_1 = true;

shift_line_buffer_array_ap_ufixed_1u_config2_s::shift_line_buffer_array_ap_ufixed_1u_config2_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buffer_Array_V_1_0_0_U = new shift_line_buffer_array_ap_ufixed_1u_config2_s_line_buffebkb("line_buffer_Array_V_1_0_0_U");
    line_buffer_Array_V_1_0_0_U->clk(ap_clk);
    line_buffer_Array_V_1_0_0_U->reset(ap_rst);
    line_buffer_Array_V_1_0_0_U->address0(ap_var_for_const0);
    line_buffer_Array_V_1_0_0_U->ce0(line_buffer_Array_V_1_0_0_ce0);
    line_buffer_Array_V_1_0_0_U->we0(line_buffer_Array_V_1_0_0_we0);
    line_buffer_Array_V_1_0_0_U->d0(in_elem_data_V_read);
    line_buffer_Array_V_1_0_0_U->q0(line_buffer_Array_V_1_0_0_q0);
    line_buffer_Array_V_1_1_0_U = new shift_line_buffer_array_ap_ufixed_1u_config2_s_line_buffebkb("line_buffer_Array_V_1_1_0_U");
    line_buffer_Array_V_1_1_0_U->clk(ap_clk);
    line_buffer_Array_V_1_1_0_U->reset(ap_rst);
    line_buffer_Array_V_1_1_0_U->address0(ap_var_for_const0);
    line_buffer_Array_V_1_1_0_U->ce0(line_buffer_Array_V_1_1_0_ce0);
    line_buffer_Array_V_1_1_0_U->we0(line_buffer_Array_V_1_1_0_we0);
    line_buffer_Array_V_1_1_0_U->d0(line_buffer_Array_V_1_0_0_q0);
    line_buffer_Array_V_1_1_0_U->q0(line_buffer_Array_V_1_1_0_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_1_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_4_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_7_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_2_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_1_1_0_q0 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_5_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( line_buffer_Array_V_1_0_0_q0 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( kernel_window_8_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( in_elem_data_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_line_buffer_Array_V_1_0_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_line_buffer_Array_V_1_0_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_line_buffer_Array_V_1_1_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_line_buffer_Array_V_1_1_0_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_ce );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shift_line_buffer_array_ap_ufixed_1u_config2_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_elem_data_V_read, "(port)in_elem_data_V_read");
    sc_trace(mVcdFile, kernel_window_1_V_read, "(port)kernel_window_1_V_read");
    sc_trace(mVcdFile, kernel_window_2_V_read, "(port)kernel_window_2_V_read");
    sc_trace(mVcdFile, kernel_window_4_V_read, "(port)kernel_window_4_V_read");
    sc_trace(mVcdFile, kernel_window_5_V_read, "(port)kernel_window_5_V_read");
    sc_trace(mVcdFile, kernel_window_7_V_read, "(port)kernel_window_7_V_read");
    sc_trace(mVcdFile, kernel_window_8_V_read, "(port)kernel_window_8_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, line_buffer_Array_V_1_0_0_ce0, "line_buffer_Array_V_1_0_0_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_1_0_0_we0, "line_buffer_Array_V_1_0_0_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_1_0_0_q0, "line_buffer_Array_V_1_0_0_q0");
    sc_trace(mVcdFile, line_buffer_Array_V_1_1_0_ce0, "line_buffer_Array_V_1_1_0_ce0");
    sc_trace(mVcdFile, line_buffer_Array_V_1_1_0_we0, "line_buffer_Array_V_1_1_0_we0");
    sc_trace(mVcdFile, line_buffer_Array_V_1_1_0_q0, "line_buffer_Array_V_1_1_0_q0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

shift_line_buffer_array_ap_ufixed_1u_config2_s::~shift_line_buffer_array_ap_ufixed_1u_config2_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete line_buffer_Array_V_1_0_0_U;
    delete line_buffer_Array_V_1_1_0_U;
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_1B;
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_0() {
    ap_return_0 = kernel_window_1_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_1() {
    ap_return_1 = kernel_window_4_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_2() {
    ap_return_2 = kernel_window_7_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_3() {
    ap_return_3 = kernel_window_2_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_4() {
    ap_return_4 = line_buffer_Array_V_1_1_0_q0.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_5() {
    ap_return_5 = kernel_window_5_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_6() {
    ap_return_6 = line_buffer_Array_V_1_0_0_q0.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_7() {
    ap_return_7 = kernel_window_8_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_return_8() {
    ap_return_8 = in_elem_data_V_read.read();
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_line_buffer_Array_V_1_0_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        line_buffer_Array_V_1_0_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_1_0_0_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_line_buffer_Array_V_1_0_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        line_buffer_Array_V_1_0_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_1_0_0_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_line_buffer_Array_V_1_1_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        line_buffer_Array_V_1_1_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_1_1_0_ce0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_line_buffer_Array_V_1_1_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        line_buffer_Array_V_1_1_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        line_buffer_Array_V_1_1_0_we0 = ap_const_logic_0;
    }
}

void shift_line_buffer_array_ap_ufixed_1u_config2_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

