AcceleratorConfig:
  Board: alveo-u50
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
Board: alveo-u50
ClockPeriod: 4
HLSConfig:
  LayerName:
    1_relu_1:
      Precision:
        result: ap_fixed<3,2>
      ReuseFactor: 1
    layer0:
      Precision: ap_ufixed<8,3>
    maxp:
      Precision: ap_fixed<3,2>
      Trace: true
    maxp_1:
      Precision: ap_fixed<3,2>
      Trace: true
    q_conv2d:
      Precision:
        bias: ap_fixed<7,1>
        weight: ap_fixed<4,2>
      ReuseFactor: 16
      Strategy: Latency
      Trace: true
    q_conv2d_1:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 16
      Strategy: Latency
      Trace: true
    q_dense:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 2
      Strategy: Resource
      Trace: true
    q_relu:
      Precision:
        result: ap_fixed<3,2>
      ReuseFactor: 1
    softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Strategy: Stable
      Trace: true
      exp_table_t: ap_fixed<12,4>
      inv_table_t: ap_fixed<12,2>
      table_size: 1024
  Model:
    Precision: ap_fixed<12,6>
    ReuseFactor: 1
    Strategy: Resource
  SkipOptimizers:
  - reshape_stream
IOType: io_stream
KerasModel: !keras_model '/home/gabri-bot/University/Git_hub/ALVEO_ML/NN_train/MNIST_Test/HLS_projects/Qkeras_pruned_CNN/hls4ml_alveo_prj/keras_model.h5'
OutputDir: /home/gabri-bot/University/Git_hub/ALVEO_ML/NN_train/MNIST_Test/HLS_projects/Qkeras_pruned_CNN/hls4ml_alveo_prj
ProjectName: myproject
Stamp: C0cB45Be
XilinxPart: xcu50-fsvh2104-2L-e
