// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_array_array_ap_fixed_12_6_5_3_0_10u_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_stream_V_data_0_V_dout,
        data_stream_V_data_0_V_empty_n,
        data_stream_V_data_0_V_read,
        data_stream_V_data_1_V_dout,
        data_stream_V_data_1_V_empty_n,
        data_stream_V_data_1_V_read,
        data_stream_V_data_2_V_dout,
        data_stream_V_data_2_V_empty_n,
        data_stream_V_data_2_V_read,
        data_stream_V_data_3_V_dout,
        data_stream_V_data_3_V_empty_n,
        data_stream_V_data_3_V_read,
        data_stream_V_data_4_V_dout,
        data_stream_V_data_4_V_empty_n,
        data_stream_V_data_4_V_read,
        data_stream_V_data_5_V_dout,
        data_stream_V_data_5_V_empty_n,
        data_stream_V_data_5_V_read,
        data_stream_V_data_6_V_dout,
        data_stream_V_data_6_V_empty_n,
        data_stream_V_data_6_V_read,
        data_stream_V_data_7_V_dout,
        data_stream_V_data_7_V_empty_n,
        data_stream_V_data_7_V_read,
        data_stream_V_data_8_V_dout,
        data_stream_V_data_8_V_empty_n,
        data_stream_V_data_8_V_read,
        data_stream_V_data_9_V_dout,
        data_stream_V_data_9_V_empty_n,
        data_stream_V_data_9_V_read,
        data_stream_V_data_10_V_dout,
        data_stream_V_data_10_V_empty_n,
        data_stream_V_data_10_V_read,
        data_stream_V_data_11_V_dout,
        data_stream_V_data_11_V_empty_n,
        data_stream_V_data_11_V_read,
        data_stream_V_data_12_V_dout,
        data_stream_V_data_12_V_empty_n,
        data_stream_V_data_12_V_read,
        data_stream_V_data_13_V_dout,
        data_stream_V_data_13_V_empty_n,
        data_stream_V_data_13_V_read,
        data_stream_V_data_14_V_dout,
        data_stream_V_data_14_V_empty_n,
        data_stream_V_data_14_V_read,
        data_stream_V_data_15_V_dout,
        data_stream_V_data_15_V_empty_n,
        data_stream_V_data_15_V_read,
        res_stream_V_data_0_V_din,
        res_stream_V_data_0_V_full_n,
        res_stream_V_data_0_V_write,
        res_stream_V_data_1_V_din,
        res_stream_V_data_1_V_full_n,
        res_stream_V_data_1_V_write,
        res_stream_V_data_2_V_din,
        res_stream_V_data_2_V_full_n,
        res_stream_V_data_2_V_write,
        res_stream_V_data_3_V_din,
        res_stream_V_data_3_V_full_n,
        res_stream_V_data_3_V_write,
        res_stream_V_data_4_V_din,
        res_stream_V_data_4_V_full_n,
        res_stream_V_data_4_V_write,
        res_stream_V_data_5_V_din,
        res_stream_V_data_5_V_full_n,
        res_stream_V_data_5_V_write,
        res_stream_V_data_6_V_din,
        res_stream_V_data_6_V_full_n,
        res_stream_V_data_6_V_write,
        res_stream_V_data_7_V_din,
        res_stream_V_data_7_V_full_n,
        res_stream_V_data_7_V_write,
        res_stream_V_data_8_V_din,
        res_stream_V_data_8_V_full_n,
        res_stream_V_data_8_V_write,
        res_stream_V_data_9_V_din,
        res_stream_V_data_9_V_full_n,
        res_stream_V_data_9_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_state4 = 5'd4;
parameter    ap_ST_fsm_state5 = 5'd8;
parameter    ap_ST_fsm_state6 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [2:0] data_stream_V_data_0_V_dout;
input   data_stream_V_data_0_V_empty_n;
output   data_stream_V_data_0_V_read;
input  [2:0] data_stream_V_data_1_V_dout;
input   data_stream_V_data_1_V_empty_n;
output   data_stream_V_data_1_V_read;
input  [2:0] data_stream_V_data_2_V_dout;
input   data_stream_V_data_2_V_empty_n;
output   data_stream_V_data_2_V_read;
input  [2:0] data_stream_V_data_3_V_dout;
input   data_stream_V_data_3_V_empty_n;
output   data_stream_V_data_3_V_read;
input  [2:0] data_stream_V_data_4_V_dout;
input   data_stream_V_data_4_V_empty_n;
output   data_stream_V_data_4_V_read;
input  [2:0] data_stream_V_data_5_V_dout;
input   data_stream_V_data_5_V_empty_n;
output   data_stream_V_data_5_V_read;
input  [2:0] data_stream_V_data_6_V_dout;
input   data_stream_V_data_6_V_empty_n;
output   data_stream_V_data_6_V_read;
input  [2:0] data_stream_V_data_7_V_dout;
input   data_stream_V_data_7_V_empty_n;
output   data_stream_V_data_7_V_read;
input  [2:0] data_stream_V_data_8_V_dout;
input   data_stream_V_data_8_V_empty_n;
output   data_stream_V_data_8_V_read;
input  [2:0] data_stream_V_data_9_V_dout;
input   data_stream_V_data_9_V_empty_n;
output   data_stream_V_data_9_V_read;
input  [2:0] data_stream_V_data_10_V_dout;
input   data_stream_V_data_10_V_empty_n;
output   data_stream_V_data_10_V_read;
input  [2:0] data_stream_V_data_11_V_dout;
input   data_stream_V_data_11_V_empty_n;
output   data_stream_V_data_11_V_read;
input  [2:0] data_stream_V_data_12_V_dout;
input   data_stream_V_data_12_V_empty_n;
output   data_stream_V_data_12_V_read;
input  [2:0] data_stream_V_data_13_V_dout;
input   data_stream_V_data_13_V_empty_n;
output   data_stream_V_data_13_V_read;
input  [2:0] data_stream_V_data_14_V_dout;
input   data_stream_V_data_14_V_empty_n;
output   data_stream_V_data_14_V_read;
input  [2:0] data_stream_V_data_15_V_dout;
input   data_stream_V_data_15_V_empty_n;
output   data_stream_V_data_15_V_read;
output  [11:0] res_stream_V_data_0_V_din;
input   res_stream_V_data_0_V_full_n;
output   res_stream_V_data_0_V_write;
output  [11:0] res_stream_V_data_1_V_din;
input   res_stream_V_data_1_V_full_n;
output   res_stream_V_data_1_V_write;
output  [11:0] res_stream_V_data_2_V_din;
input   res_stream_V_data_2_V_full_n;
output   res_stream_V_data_2_V_write;
output  [11:0] res_stream_V_data_3_V_din;
input   res_stream_V_data_3_V_full_n;
output   res_stream_V_data_3_V_write;
output  [11:0] res_stream_V_data_4_V_din;
input   res_stream_V_data_4_V_full_n;
output   res_stream_V_data_4_V_write;
output  [11:0] res_stream_V_data_5_V_din;
input   res_stream_V_data_5_V_full_n;
output   res_stream_V_data_5_V_write;
output  [11:0] res_stream_V_data_6_V_din;
input   res_stream_V_data_6_V_full_n;
output   res_stream_V_data_6_V_write;
output  [11:0] res_stream_V_data_7_V_din;
input   res_stream_V_data_7_V_full_n;
output   res_stream_V_data_7_V_write;
output  [11:0] res_stream_V_data_8_V_din;
input   res_stream_V_data_8_V_full_n;
output   res_stream_V_data_8_V_write;
output  [11:0] res_stream_V_data_9_V_din;
input   res_stream_V_data_9_V_full_n;
output   res_stream_V_data_9_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_stream_V_data_0_V_read;
reg data_stream_V_data_1_V_read;
reg data_stream_V_data_2_V_read;
reg data_stream_V_data_3_V_read;
reg data_stream_V_data_4_V_read;
reg data_stream_V_data_5_V_read;
reg data_stream_V_data_6_V_read;
reg data_stream_V_data_7_V_read;
reg data_stream_V_data_8_V_read;
reg data_stream_V_data_9_V_read;
reg data_stream_V_data_10_V_read;
reg data_stream_V_data_11_V_read;
reg data_stream_V_data_12_V_read;
reg data_stream_V_data_13_V_read;
reg data_stream_V_data_14_V_read;
reg data_stream_V_data_15_V_read;
reg res_stream_V_data_0_V_write;
reg res_stream_V_data_1_V_write;
reg res_stream_V_data_2_V_write;
reg res_stream_V_data_3_V_write;
reg res_stream_V_data_4_V_write;
reg res_stream_V_data_5_V_write;
reg res_stream_V_data_6_V_write;
reg res_stream_V_data_7_V_write;
reg res_stream_V_data_8_V_write;
reg res_stream_V_data_9_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    data_stream_V_data_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    data_stream_V_data_1_V_blk_n;
reg    data_stream_V_data_2_V_blk_n;
reg    data_stream_V_data_3_V_blk_n;
reg    data_stream_V_data_4_V_blk_n;
reg    data_stream_V_data_5_V_blk_n;
reg    data_stream_V_data_6_V_blk_n;
reg    data_stream_V_data_7_V_blk_n;
reg    data_stream_V_data_8_V_blk_n;
reg    data_stream_V_data_9_V_blk_n;
reg    data_stream_V_data_10_V_blk_n;
reg    data_stream_V_data_11_V_blk_n;
reg    data_stream_V_data_12_V_blk_n;
reg    data_stream_V_data_13_V_blk_n;
reg    data_stream_V_data_14_V_blk_n;
reg    data_stream_V_data_15_V_blk_n;
reg    res_stream_V_data_0_V_blk_n;
wire    ap_CS_fsm_state6;
reg    res_stream_V_data_1_V_blk_n;
reg    res_stream_V_data_2_V_blk_n;
reg    res_stream_V_data_3_V_blk_n;
reg    res_stream_V_data_4_V_blk_n;
reg    res_stream_V_data_5_V_blk_n;
reg    res_stream_V_data_6_V_blk_n;
reg    res_stream_V_data_7_V_blk_n;
reg    res_stream_V_data_8_V_blk_n;
reg    res_stream_V_data_9_V_blk_n;
reg   [4:0] i_in_0_reg_1816;
wire   [0:0] icmp_ln41_fu_2234_p2;
reg   [0:0] icmp_ln41_reg_8350;
wire    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op843;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] i_in_fu_2240_p2;
reg   [4:0] i_in_reg_8354;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state4;
reg   [11:0] tmp_data_0_V_reg_10359;
wire    ap_CS_fsm_state5;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_ready;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_done;
reg   [11:0] tmp_data_1_V_reg_10364;
reg   [11:0] tmp_data_2_V_reg_10369;
reg   [11:0] tmp_data_3_V_reg_10374;
reg   [11:0] tmp_data_4_V_reg_10379;
reg   [11:0] tmp_data_5_V_reg_10384;
reg   [11:0] tmp_data_6_V_reg_10389;
reg   [11:0] tmp_data_7_V_reg_10394;
reg   [11:0] tmp_data_8_V_reg_10399;
reg   [11:0] tmp_data_9_V_reg_10404;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start;
wire    grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_idle;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_0;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_1;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_2;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_3;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_4;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_5;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_6;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_7;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_8;
wire   [11:0] grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_9;
reg   [4:0] ap_phi_mux_i_in_0_phi_fu_1820_p4;
reg    grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg;
reg   [2:0] data_384_V_fu_146;
reg   [2:0] data_385_V_fu_150;
reg   [2:0] data_386_V_fu_154;
reg   [2:0] data_387_V_fu_158;
reg   [2:0] data_388_V_fu_162;
reg   [2:0] data_389_V_fu_166;
reg   [2:0] data_390_V_fu_170;
reg   [2:0] data_391_V_fu_174;
reg   [2:0] data_392_V_fu_178;
reg   [2:0] data_393_V_fu_182;
reg   [2:0] data_394_V_fu_186;
reg   [2:0] data_395_V_fu_190;
reg   [2:0] data_396_V_fu_194;
reg   [2:0] data_397_V_fu_198;
reg   [2:0] data_398_V_fu_202;
reg   [2:0] data_399_V_fu_206;
reg   [2:0] data_384_V_1_fu_210;
reg   [2:0] data_385_V_1_fu_214;
reg   [2:0] data_386_V_1_fu_218;
reg   [2:0] data_387_V_1_fu_222;
reg   [2:0] data_388_V_1_fu_226;
reg   [2:0] data_389_V_1_fu_230;
reg   [2:0] data_390_V_1_fu_234;
reg   [2:0] data_391_V_1_fu_238;
reg   [2:0] data_392_V_1_fu_242;
reg   [2:0] data_393_V_1_fu_246;
reg   [2:0] data_394_V_1_fu_250;
reg   [2:0] data_395_V_1_fu_254;
reg   [2:0] data_396_V_1_fu_258;
reg   [2:0] data_397_V_1_fu_262;
reg   [2:0] data_398_V_1_fu_266;
reg   [2:0] data_399_V_1_fu_270;
reg   [2:0] data_384_V_2_fu_274;
reg   [2:0] data_385_V_2_fu_278;
reg   [2:0] data_386_V_2_fu_282;
reg   [2:0] data_387_V_2_fu_286;
reg   [2:0] data_388_V_2_fu_290;
reg   [2:0] data_389_V_2_fu_294;
reg   [2:0] data_390_V_2_fu_298;
reg   [2:0] data_391_V_2_fu_302;
reg   [2:0] data_392_V_2_fu_306;
reg   [2:0] data_393_V_2_fu_310;
reg   [2:0] data_394_V_2_fu_314;
reg   [2:0] data_395_V_2_fu_318;
reg   [2:0] data_396_V_2_fu_322;
reg   [2:0] data_397_V_2_fu_326;
reg   [2:0] data_398_V_2_fu_330;
reg   [2:0] data_399_V_2_fu_334;
reg   [2:0] data_384_V_3_fu_338;
reg   [2:0] data_385_V_3_fu_342;
reg   [2:0] data_386_V_3_fu_346;
reg   [2:0] data_387_V_3_fu_350;
reg   [2:0] data_388_V_3_fu_354;
reg   [2:0] data_389_V_3_fu_358;
reg   [2:0] data_390_V_3_fu_362;
reg   [2:0] data_391_V_3_fu_366;
reg   [2:0] data_392_V_3_fu_370;
reg   [2:0] data_393_V_3_fu_374;
reg   [2:0] data_394_V_3_fu_378;
reg   [2:0] data_395_V_3_fu_382;
reg   [2:0] data_396_V_3_fu_386;
reg   [2:0] data_397_V_3_fu_390;
reg   [2:0] data_398_V_3_fu_394;
reg   [2:0] data_399_V_3_fu_398;
reg   [2:0] data_384_V_4_fu_402;
reg   [2:0] data_385_V_4_fu_406;
reg   [2:0] data_386_V_4_fu_410;
reg   [2:0] data_387_V_4_fu_414;
reg   [2:0] data_388_V_4_fu_418;
reg   [2:0] data_389_V_4_fu_422;
reg   [2:0] data_390_V_4_fu_426;
reg   [2:0] data_391_V_4_fu_430;
reg   [2:0] data_392_V_4_fu_434;
reg   [2:0] data_393_V_4_fu_438;
reg   [2:0] data_394_V_4_fu_442;
reg   [2:0] data_395_V_4_fu_446;
reg   [2:0] data_396_V_4_fu_450;
reg   [2:0] data_397_V_4_fu_454;
reg   [2:0] data_398_V_4_fu_458;
reg   [2:0] data_399_V_4_fu_462;
reg   [2:0] data_384_V_5_fu_466;
reg   [2:0] data_385_V_5_fu_470;
reg   [2:0] data_386_V_5_fu_474;
reg   [2:0] data_387_V_5_fu_478;
reg   [2:0] data_388_V_5_fu_482;
reg   [2:0] data_389_V_5_fu_486;
reg   [2:0] data_390_V_5_fu_490;
reg   [2:0] data_391_V_5_fu_494;
reg   [2:0] data_392_V_5_fu_498;
reg   [2:0] data_393_V_5_fu_502;
reg   [2:0] data_394_V_5_fu_506;
reg   [2:0] data_395_V_5_fu_510;
reg   [2:0] data_396_V_5_fu_514;
reg   [2:0] data_397_V_5_fu_518;
reg   [2:0] data_398_V_5_fu_522;
reg   [2:0] data_399_V_5_fu_526;
reg   [2:0] data_384_V_6_fu_530;
reg   [2:0] data_385_V_6_fu_534;
reg   [2:0] data_386_V_6_fu_538;
reg   [2:0] data_387_V_6_fu_542;
reg   [2:0] data_388_V_6_fu_546;
reg   [2:0] data_389_V_6_fu_550;
reg   [2:0] data_390_V_6_fu_554;
reg   [2:0] data_391_V_6_fu_558;
reg   [2:0] data_392_V_6_fu_562;
reg   [2:0] data_393_V_6_fu_566;
reg   [2:0] data_394_V_6_fu_570;
reg   [2:0] data_395_V_6_fu_574;
reg   [2:0] data_396_V_6_fu_578;
reg   [2:0] data_397_V_6_fu_582;
reg   [2:0] data_398_V_6_fu_586;
reg   [2:0] data_399_V_6_fu_590;
reg   [2:0] data_384_V_7_fu_594;
reg   [2:0] data_385_V_7_fu_598;
reg   [2:0] data_386_V_7_fu_602;
reg   [2:0] data_387_V_7_fu_606;
reg   [2:0] data_388_V_7_fu_610;
reg   [2:0] data_389_V_7_fu_614;
reg   [2:0] data_390_V_7_fu_618;
reg   [2:0] data_391_V_7_fu_622;
reg   [2:0] data_392_V_7_fu_626;
reg   [2:0] data_393_V_7_fu_630;
reg   [2:0] data_394_V_7_fu_634;
reg   [2:0] data_395_V_7_fu_638;
reg   [2:0] data_396_V_7_fu_642;
reg   [2:0] data_397_V_7_fu_646;
reg   [2:0] data_398_V_7_fu_650;
reg   [2:0] data_399_V_7_fu_654;
reg   [2:0] data_384_V_8_fu_658;
reg   [2:0] data_385_V_8_fu_662;
reg   [2:0] data_386_V_8_fu_666;
reg   [2:0] data_387_V_8_fu_670;
reg   [2:0] data_388_V_8_fu_674;
reg   [2:0] data_389_V_8_fu_678;
reg   [2:0] data_390_V_8_fu_682;
reg   [2:0] data_391_V_8_fu_686;
reg   [2:0] data_392_V_8_fu_690;
reg   [2:0] data_393_V_8_fu_694;
reg   [2:0] data_394_V_8_fu_698;
reg   [2:0] data_395_V_8_fu_702;
reg   [2:0] data_396_V_8_fu_706;
reg   [2:0] data_397_V_8_fu_710;
reg   [2:0] data_398_V_8_fu_714;
reg   [2:0] data_399_V_8_fu_718;
reg   [2:0] data_384_V_9_fu_722;
reg   [2:0] data_385_V_9_fu_726;
reg   [2:0] data_386_V_9_fu_730;
reg   [2:0] data_387_V_9_fu_734;
reg   [2:0] data_388_V_9_fu_738;
reg   [2:0] data_389_V_9_fu_742;
reg   [2:0] data_390_V_9_fu_746;
reg   [2:0] data_391_V_9_fu_750;
reg   [2:0] data_392_V_9_fu_754;
reg   [2:0] data_393_V_9_fu_758;
reg   [2:0] data_394_V_9_fu_762;
reg   [2:0] data_395_V_9_fu_766;
reg   [2:0] data_396_V_9_fu_770;
reg   [2:0] data_397_V_9_fu_774;
reg   [2:0] data_398_V_9_fu_778;
reg   [2:0] data_399_V_9_fu_782;
reg   [2:0] data_384_V_10_fu_786;
reg   [2:0] data_385_V_10_fu_790;
reg   [2:0] data_386_V_10_fu_794;
reg   [2:0] data_387_V_10_fu_798;
reg   [2:0] data_388_V_10_fu_802;
reg   [2:0] data_389_V_10_fu_806;
reg   [2:0] data_390_V_10_fu_810;
reg   [2:0] data_391_V_10_fu_814;
reg   [2:0] data_392_V_10_fu_818;
reg   [2:0] data_393_V_10_fu_822;
reg   [2:0] data_394_V_10_fu_826;
reg   [2:0] data_395_V_10_fu_830;
reg   [2:0] data_396_V_10_fu_834;
reg   [2:0] data_397_V_10_fu_838;
reg   [2:0] data_398_V_10_fu_842;
reg   [2:0] data_399_V_10_fu_846;
reg   [2:0] data_384_V_11_fu_850;
reg   [2:0] data_385_V_11_fu_854;
reg   [2:0] data_386_V_11_fu_858;
reg   [2:0] data_387_V_11_fu_862;
reg   [2:0] data_388_V_11_fu_866;
reg   [2:0] data_389_V_11_fu_870;
reg   [2:0] data_390_V_11_fu_874;
reg   [2:0] data_391_V_11_fu_878;
reg   [2:0] data_392_V_11_fu_882;
reg   [2:0] data_393_V_11_fu_886;
reg   [2:0] data_394_V_11_fu_890;
reg   [2:0] data_395_V_11_fu_894;
reg   [2:0] data_396_V_11_fu_898;
reg   [2:0] data_397_V_11_fu_902;
reg   [2:0] data_398_V_11_fu_906;
reg   [2:0] data_399_V_11_fu_910;
reg   [2:0] data_384_V_12_fu_914;
reg   [2:0] data_385_V_12_fu_918;
reg   [2:0] data_386_V_12_fu_922;
reg   [2:0] data_387_V_12_fu_926;
reg   [2:0] data_388_V_12_fu_930;
reg   [2:0] data_389_V_12_fu_934;
reg   [2:0] data_390_V_12_fu_938;
reg   [2:0] data_391_V_12_fu_942;
reg   [2:0] data_392_V_12_fu_946;
reg   [2:0] data_393_V_12_fu_950;
reg   [2:0] data_394_V_12_fu_954;
reg   [2:0] data_395_V_12_fu_958;
reg   [2:0] data_396_V_12_fu_962;
reg   [2:0] data_397_V_12_fu_966;
reg   [2:0] data_398_V_12_fu_970;
reg   [2:0] data_399_V_12_fu_974;
reg   [2:0] data_384_V_13_fu_978;
reg   [2:0] data_385_V_13_fu_982;
reg   [2:0] data_386_V_13_fu_986;
reg   [2:0] data_387_V_13_fu_990;
reg   [2:0] data_388_V_13_fu_994;
reg   [2:0] data_389_V_13_fu_998;
reg   [2:0] data_390_V_13_fu_1002;
reg   [2:0] data_391_V_13_fu_1006;
reg   [2:0] data_392_V_13_fu_1010;
reg   [2:0] data_393_V_13_fu_1014;
reg   [2:0] data_394_V_13_fu_1018;
reg   [2:0] data_395_V_13_fu_1022;
reg   [2:0] data_396_V_13_fu_1026;
reg   [2:0] data_397_V_13_fu_1030;
reg   [2:0] data_398_V_13_fu_1034;
reg   [2:0] data_399_V_13_fu_1038;
reg   [2:0] data_384_V_14_fu_1042;
reg   [2:0] data_385_V_14_fu_1046;
reg   [2:0] data_386_V_14_fu_1050;
reg   [2:0] data_387_V_14_fu_1054;
reg   [2:0] data_388_V_14_fu_1058;
reg   [2:0] data_389_V_14_fu_1062;
reg   [2:0] data_390_V_14_fu_1066;
reg   [2:0] data_391_V_14_fu_1070;
reg   [2:0] data_392_V_14_fu_1074;
reg   [2:0] data_393_V_14_fu_1078;
reg   [2:0] data_394_V_14_fu_1082;
reg   [2:0] data_395_V_14_fu_1086;
reg   [2:0] data_396_V_14_fu_1090;
reg   [2:0] data_397_V_14_fu_1094;
reg   [2:0] data_398_V_14_fu_1098;
reg   [2:0] data_399_V_14_fu_1102;
reg   [2:0] data_384_V_15_fu_1106;
reg   [2:0] data_385_V_15_fu_1110;
reg   [2:0] data_386_V_15_fu_1114;
reg   [2:0] data_387_V_15_fu_1118;
reg   [2:0] data_388_V_15_fu_1122;
reg   [2:0] data_389_V_15_fu_1126;
reg   [2:0] data_390_V_15_fu_1130;
reg   [2:0] data_391_V_15_fu_1134;
reg   [2:0] data_392_V_15_fu_1138;
reg   [2:0] data_393_V_15_fu_1142;
reg   [2:0] data_394_V_15_fu_1146;
reg   [2:0] data_395_V_15_fu_1150;
reg   [2:0] data_396_V_15_fu_1154;
reg   [2:0] data_397_V_15_fu_1158;
reg   [2:0] data_398_V_15_fu_1162;
reg   [2:0] data_399_V_15_fu_1166;
reg   [2:0] data_384_V_16_fu_1170;
reg   [2:0] data_385_V_16_fu_1174;
reg   [2:0] data_386_V_16_fu_1178;
reg   [2:0] data_387_V_16_fu_1182;
reg   [2:0] data_388_V_16_fu_1186;
reg   [2:0] data_389_V_16_fu_1190;
reg   [2:0] data_390_V_16_fu_1194;
reg   [2:0] data_391_V_16_fu_1198;
reg   [2:0] data_392_V_16_fu_1202;
reg   [2:0] data_393_V_16_fu_1206;
reg   [2:0] data_394_V_16_fu_1210;
reg   [2:0] data_395_V_16_fu_1214;
reg   [2:0] data_396_V_16_fu_1218;
reg   [2:0] data_397_V_16_fu_1222;
reg   [2:0] data_398_V_16_fu_1226;
reg   [2:0] data_399_V_16_fu_1230;
reg   [2:0] data_384_V_17_fu_1234;
reg   [2:0] data_385_V_17_fu_1238;
reg   [2:0] data_386_V_17_fu_1242;
reg   [2:0] data_387_V_17_fu_1246;
reg   [2:0] data_388_V_17_fu_1250;
reg   [2:0] data_389_V_17_fu_1254;
reg   [2:0] data_390_V_17_fu_1258;
reg   [2:0] data_391_V_17_fu_1262;
reg   [2:0] data_392_V_17_fu_1266;
reg   [2:0] data_393_V_17_fu_1270;
reg   [2:0] data_394_V_17_fu_1274;
reg   [2:0] data_395_V_17_fu_1278;
reg   [2:0] data_396_V_17_fu_1282;
reg   [2:0] data_397_V_17_fu_1286;
reg   [2:0] data_398_V_17_fu_1290;
reg   [2:0] data_399_V_17_fu_1294;
reg   [2:0] data_384_V_18_fu_1298;
reg   [2:0] data_385_V_18_fu_1302;
reg   [2:0] data_386_V_18_fu_1306;
reg   [2:0] data_387_V_18_fu_1310;
reg   [2:0] data_388_V_18_fu_1314;
reg   [2:0] data_389_V_18_fu_1318;
reg   [2:0] data_390_V_18_fu_1322;
reg   [2:0] data_391_V_18_fu_1326;
reg   [2:0] data_392_V_18_fu_1330;
reg   [2:0] data_393_V_18_fu_1334;
reg   [2:0] data_394_V_18_fu_1338;
reg   [2:0] data_395_V_18_fu_1342;
reg   [2:0] data_396_V_18_fu_1346;
reg   [2:0] data_397_V_18_fu_1350;
reg   [2:0] data_398_V_18_fu_1354;
reg   [2:0] data_399_V_18_fu_1358;
reg   [2:0] data_384_V_19_fu_1362;
reg   [2:0] data_385_V_19_fu_1366;
reg   [2:0] data_386_V_19_fu_1370;
reg   [2:0] data_387_V_19_fu_1374;
reg   [2:0] data_388_V_19_fu_1378;
reg   [2:0] data_389_V_19_fu_1382;
reg   [2:0] data_390_V_19_fu_1386;
reg   [2:0] data_391_V_19_fu_1390;
reg   [2:0] data_392_V_19_fu_1394;
reg   [2:0] data_393_V_19_fu_1398;
reg   [2:0] data_394_V_19_fu_1402;
reg   [2:0] data_395_V_19_fu_1406;
reg   [2:0] data_396_V_19_fu_1410;
reg   [2:0] data_397_V_19_fu_1414;
reg   [2:0] data_398_V_19_fu_1418;
reg   [2:0] data_399_V_19_fu_1422;
reg   [2:0] data_384_V_20_fu_1426;
reg   [2:0] data_385_V_20_fu_1430;
reg   [2:0] data_386_V_20_fu_1434;
reg   [2:0] data_387_V_20_fu_1438;
reg   [2:0] data_388_V_20_fu_1442;
reg   [2:0] data_389_V_20_fu_1446;
reg   [2:0] data_390_V_20_fu_1450;
reg   [2:0] data_391_V_20_fu_1454;
reg   [2:0] data_392_V_20_fu_1458;
reg   [2:0] data_393_V_20_fu_1462;
reg   [2:0] data_394_V_20_fu_1466;
reg   [2:0] data_395_V_20_fu_1470;
reg   [2:0] data_396_V_20_fu_1474;
reg   [2:0] data_397_V_20_fu_1478;
reg   [2:0] data_398_V_20_fu_1482;
reg   [2:0] data_399_V_20_fu_1486;
reg   [2:0] data_384_V_21_fu_1490;
reg   [2:0] data_385_V_21_fu_1494;
reg   [2:0] data_386_V_21_fu_1498;
reg   [2:0] data_387_V_21_fu_1502;
reg   [2:0] data_388_V_21_fu_1506;
reg   [2:0] data_389_V_21_fu_1510;
reg   [2:0] data_390_V_21_fu_1514;
reg   [2:0] data_391_V_21_fu_1518;
reg   [2:0] data_392_V_21_fu_1522;
reg   [2:0] data_393_V_21_fu_1526;
reg   [2:0] data_394_V_21_fu_1530;
reg   [2:0] data_395_V_21_fu_1534;
reg   [2:0] data_396_V_21_fu_1538;
reg   [2:0] data_397_V_21_fu_1542;
reg   [2:0] data_398_V_21_fu_1546;
reg   [2:0] data_399_V_21_fu_1550;
reg   [2:0] data_384_V_22_fu_1554;
reg   [2:0] data_385_V_22_fu_1558;
reg   [2:0] data_386_V_22_fu_1562;
reg   [2:0] data_387_V_22_fu_1566;
reg   [2:0] data_388_V_22_fu_1570;
reg   [2:0] data_389_V_22_fu_1574;
reg   [2:0] data_390_V_22_fu_1578;
reg   [2:0] data_391_V_22_fu_1582;
reg   [2:0] data_392_V_22_fu_1586;
reg   [2:0] data_393_V_22_fu_1590;
reg   [2:0] data_394_V_22_fu_1594;
reg   [2:0] data_395_V_22_fu_1598;
reg   [2:0] data_396_V_22_fu_1602;
reg   [2:0] data_397_V_22_fu_1606;
reg   [2:0] data_398_V_22_fu_1610;
reg   [2:0] data_399_V_22_fu_1614;
reg   [2:0] data_384_V_23_fu_1618;
reg   [2:0] data_385_V_23_fu_1622;
reg   [2:0] data_386_V_23_fu_1626;
reg   [2:0] data_387_V_23_fu_1630;
reg   [2:0] data_388_V_23_fu_1634;
reg   [2:0] data_389_V_23_fu_1638;
reg   [2:0] data_390_V_23_fu_1642;
reg   [2:0] data_391_V_23_fu_1646;
reg   [2:0] data_392_V_23_fu_1650;
reg   [2:0] data_393_V_23_fu_1654;
reg   [2:0] data_394_V_23_fu_1658;
reg   [2:0] data_395_V_23_fu_1662;
reg   [2:0] data_396_V_23_fu_1666;
reg   [2:0] data_397_V_23_fu_1670;
reg   [2:0] data_398_V_23_fu_1674;
reg   [2:0] data_399_V_23_fu_1678;
reg   [2:0] data_384_V_24_fu_1682;
reg   [2:0] data_385_V_24_fu_1686;
reg   [2:0] data_386_V_24_fu_1690;
reg   [2:0] data_387_V_24_fu_1694;
reg   [2:0] data_388_V_24_fu_1698;
reg   [2:0] data_389_V_24_fu_1702;
reg   [2:0] data_390_V_24_fu_1706;
reg   [2:0] data_391_V_24_fu_1710;
reg   [2:0] data_392_V_24_fu_1714;
reg   [2:0] data_393_V_24_fu_1718;
reg   [2:0] data_394_V_24_fu_1722;
reg   [2:0] data_395_V_24_fu_1726;
reg   [2:0] data_396_V_24_fu_1730;
reg   [2:0] data_397_V_24_fu_1734;
reg   [2:0] data_398_V_24_fu_1738;
reg   [2:0] data_399_V_24_fu_1742;
wire    io_acc_block_signal_op1690;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg = 1'b0;
end

dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start),
    .ap_done(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_done),
    .ap_idle(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_idle),
    .ap_ready(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_ready),
    .data_0_V_read(data_384_V_fu_146),
    .data_1_V_read(data_385_V_fu_150),
    .data_2_V_read(data_386_V_fu_154),
    .data_3_V_read(data_387_V_fu_158),
    .data_4_V_read(data_388_V_fu_162),
    .data_5_V_read(data_389_V_fu_166),
    .data_6_V_read(data_390_V_fu_170),
    .data_7_V_read(data_391_V_fu_174),
    .data_8_V_read(data_392_V_fu_178),
    .data_9_V_read(data_393_V_fu_182),
    .data_10_V_read(data_394_V_fu_186),
    .data_11_V_read(data_395_V_fu_190),
    .data_12_V_read(data_396_V_fu_194),
    .data_13_V_read(data_397_V_fu_198),
    .data_14_V_read(data_398_V_fu_202),
    .data_15_V_read(data_399_V_fu_206),
    .data_16_V_read(data_384_V_1_fu_210),
    .data_17_V_read(data_385_V_1_fu_214),
    .data_18_V_read(data_386_V_1_fu_218),
    .data_19_V_read(data_387_V_1_fu_222),
    .data_20_V_read(data_388_V_1_fu_226),
    .data_21_V_read(data_389_V_1_fu_230),
    .data_22_V_read(data_390_V_1_fu_234),
    .data_23_V_read(data_391_V_1_fu_238),
    .data_24_V_read(data_392_V_1_fu_242),
    .data_25_V_read(data_393_V_1_fu_246),
    .data_26_V_read(data_394_V_1_fu_250),
    .data_27_V_read(data_395_V_1_fu_254),
    .data_28_V_read(data_396_V_1_fu_258),
    .data_29_V_read(data_397_V_1_fu_262),
    .data_30_V_read(data_398_V_1_fu_266),
    .data_31_V_read(data_399_V_1_fu_270),
    .data_32_V_read(data_384_V_2_fu_274),
    .data_33_V_read(data_385_V_2_fu_278),
    .data_34_V_read(data_386_V_2_fu_282),
    .data_35_V_read(data_387_V_2_fu_286),
    .data_36_V_read(data_388_V_2_fu_290),
    .data_37_V_read(data_389_V_2_fu_294),
    .data_38_V_read(data_390_V_2_fu_298),
    .data_39_V_read(data_391_V_2_fu_302),
    .data_40_V_read(data_392_V_2_fu_306),
    .data_41_V_read(data_393_V_2_fu_310),
    .data_42_V_read(data_394_V_2_fu_314),
    .data_43_V_read(data_395_V_2_fu_318),
    .data_44_V_read(data_396_V_2_fu_322),
    .data_45_V_read(data_397_V_2_fu_326),
    .data_46_V_read(data_398_V_2_fu_330),
    .data_47_V_read(data_399_V_2_fu_334),
    .data_48_V_read(data_384_V_3_fu_338),
    .data_49_V_read(data_385_V_3_fu_342),
    .data_50_V_read(data_386_V_3_fu_346),
    .data_51_V_read(data_387_V_3_fu_350),
    .data_52_V_read(data_388_V_3_fu_354),
    .data_53_V_read(data_389_V_3_fu_358),
    .data_54_V_read(data_390_V_3_fu_362),
    .data_55_V_read(data_391_V_3_fu_366),
    .data_56_V_read(data_392_V_3_fu_370),
    .data_57_V_read(data_393_V_3_fu_374),
    .data_58_V_read(data_394_V_3_fu_378),
    .data_59_V_read(data_395_V_3_fu_382),
    .data_60_V_read(data_396_V_3_fu_386),
    .data_61_V_read(data_397_V_3_fu_390),
    .data_62_V_read(data_398_V_3_fu_394),
    .data_63_V_read(data_399_V_3_fu_398),
    .data_64_V_read(data_384_V_4_fu_402),
    .data_65_V_read(data_385_V_4_fu_406),
    .data_66_V_read(data_386_V_4_fu_410),
    .data_67_V_read(data_387_V_4_fu_414),
    .data_68_V_read(data_388_V_4_fu_418),
    .data_69_V_read(data_389_V_4_fu_422),
    .data_70_V_read(data_390_V_4_fu_426),
    .data_71_V_read(data_391_V_4_fu_430),
    .data_72_V_read(data_392_V_4_fu_434),
    .data_73_V_read(data_393_V_4_fu_438),
    .data_74_V_read(data_394_V_4_fu_442),
    .data_75_V_read(data_395_V_4_fu_446),
    .data_76_V_read(data_396_V_4_fu_450),
    .data_77_V_read(data_397_V_4_fu_454),
    .data_78_V_read(data_398_V_4_fu_458),
    .data_79_V_read(data_399_V_4_fu_462),
    .data_80_V_read(data_384_V_5_fu_466),
    .data_81_V_read(data_385_V_5_fu_470),
    .data_82_V_read(data_386_V_5_fu_474),
    .data_83_V_read(data_387_V_5_fu_478),
    .data_84_V_read(data_388_V_5_fu_482),
    .data_85_V_read(data_389_V_5_fu_486),
    .data_86_V_read(data_390_V_5_fu_490),
    .data_87_V_read(data_391_V_5_fu_494),
    .data_88_V_read(data_392_V_5_fu_498),
    .data_89_V_read(data_393_V_5_fu_502),
    .data_90_V_read(data_394_V_5_fu_506),
    .data_91_V_read(data_395_V_5_fu_510),
    .data_92_V_read(data_396_V_5_fu_514),
    .data_93_V_read(data_397_V_5_fu_518),
    .data_94_V_read(data_398_V_5_fu_522),
    .data_95_V_read(data_399_V_5_fu_526),
    .data_96_V_read(data_384_V_6_fu_530),
    .data_97_V_read(data_385_V_6_fu_534),
    .data_98_V_read(data_386_V_6_fu_538),
    .data_99_V_read(data_387_V_6_fu_542),
    .data_100_V_read(data_388_V_6_fu_546),
    .data_101_V_read(data_389_V_6_fu_550),
    .data_102_V_read(data_390_V_6_fu_554),
    .data_103_V_read(data_391_V_6_fu_558),
    .data_104_V_read(data_392_V_6_fu_562),
    .data_105_V_read(data_393_V_6_fu_566),
    .data_106_V_read(data_394_V_6_fu_570),
    .data_107_V_read(data_395_V_6_fu_574),
    .data_108_V_read(data_396_V_6_fu_578),
    .data_109_V_read(data_397_V_6_fu_582),
    .data_110_V_read(data_398_V_6_fu_586),
    .data_111_V_read(data_399_V_6_fu_590),
    .data_112_V_read(data_384_V_7_fu_594),
    .data_113_V_read(data_385_V_7_fu_598),
    .data_114_V_read(data_386_V_7_fu_602),
    .data_115_V_read(data_387_V_7_fu_606),
    .data_116_V_read(data_388_V_7_fu_610),
    .data_117_V_read(data_389_V_7_fu_614),
    .data_118_V_read(data_390_V_7_fu_618),
    .data_119_V_read(data_391_V_7_fu_622),
    .data_120_V_read(data_392_V_7_fu_626),
    .data_121_V_read(data_393_V_7_fu_630),
    .data_122_V_read(data_394_V_7_fu_634),
    .data_123_V_read(data_395_V_7_fu_638),
    .data_124_V_read(data_396_V_7_fu_642),
    .data_125_V_read(data_397_V_7_fu_646),
    .data_126_V_read(data_398_V_7_fu_650),
    .data_127_V_read(data_399_V_7_fu_654),
    .data_128_V_read(data_384_V_8_fu_658),
    .data_129_V_read(data_385_V_8_fu_662),
    .data_130_V_read(data_386_V_8_fu_666),
    .data_131_V_read(data_387_V_8_fu_670),
    .data_132_V_read(data_388_V_8_fu_674),
    .data_133_V_read(data_389_V_8_fu_678),
    .data_134_V_read(data_390_V_8_fu_682),
    .data_135_V_read(data_391_V_8_fu_686),
    .data_136_V_read(data_392_V_8_fu_690),
    .data_137_V_read(data_393_V_8_fu_694),
    .data_138_V_read(data_394_V_8_fu_698),
    .data_139_V_read(data_395_V_8_fu_702),
    .data_140_V_read(data_396_V_8_fu_706),
    .data_141_V_read(data_397_V_8_fu_710),
    .data_142_V_read(data_398_V_8_fu_714),
    .data_143_V_read(data_399_V_8_fu_718),
    .data_144_V_read(data_384_V_9_fu_722),
    .data_145_V_read(data_385_V_9_fu_726),
    .data_146_V_read(data_386_V_9_fu_730),
    .data_147_V_read(data_387_V_9_fu_734),
    .data_148_V_read(data_388_V_9_fu_738),
    .data_149_V_read(data_389_V_9_fu_742),
    .data_150_V_read(data_390_V_9_fu_746),
    .data_151_V_read(data_391_V_9_fu_750),
    .data_152_V_read(data_392_V_9_fu_754),
    .data_153_V_read(data_393_V_9_fu_758),
    .data_154_V_read(data_394_V_9_fu_762),
    .data_155_V_read(data_395_V_9_fu_766),
    .data_156_V_read(data_396_V_9_fu_770),
    .data_157_V_read(data_397_V_9_fu_774),
    .data_158_V_read(data_398_V_9_fu_778),
    .data_159_V_read(data_399_V_9_fu_782),
    .data_160_V_read(data_384_V_10_fu_786),
    .data_161_V_read(data_385_V_10_fu_790),
    .data_162_V_read(data_386_V_10_fu_794),
    .data_163_V_read(data_387_V_10_fu_798),
    .data_164_V_read(data_388_V_10_fu_802),
    .data_165_V_read(data_389_V_10_fu_806),
    .data_166_V_read(data_390_V_10_fu_810),
    .data_167_V_read(data_391_V_10_fu_814),
    .data_168_V_read(data_392_V_10_fu_818),
    .data_169_V_read(data_393_V_10_fu_822),
    .data_170_V_read(data_394_V_10_fu_826),
    .data_171_V_read(data_395_V_10_fu_830),
    .data_172_V_read(data_396_V_10_fu_834),
    .data_173_V_read(data_397_V_10_fu_838),
    .data_174_V_read(data_398_V_10_fu_842),
    .data_175_V_read(data_399_V_10_fu_846),
    .data_176_V_read(data_384_V_11_fu_850),
    .data_177_V_read(data_385_V_11_fu_854),
    .data_178_V_read(data_386_V_11_fu_858),
    .data_179_V_read(data_387_V_11_fu_862),
    .data_180_V_read(data_388_V_11_fu_866),
    .data_181_V_read(data_389_V_11_fu_870),
    .data_182_V_read(data_390_V_11_fu_874),
    .data_183_V_read(data_391_V_11_fu_878),
    .data_184_V_read(data_392_V_11_fu_882),
    .data_185_V_read(data_393_V_11_fu_886),
    .data_186_V_read(data_394_V_11_fu_890),
    .data_187_V_read(data_395_V_11_fu_894),
    .data_188_V_read(data_396_V_11_fu_898),
    .data_189_V_read(data_397_V_11_fu_902),
    .data_190_V_read(data_398_V_11_fu_906),
    .data_191_V_read(data_399_V_11_fu_910),
    .data_192_V_read(data_384_V_12_fu_914),
    .data_193_V_read(data_385_V_12_fu_918),
    .data_194_V_read(data_386_V_12_fu_922),
    .data_195_V_read(data_387_V_12_fu_926),
    .data_196_V_read(data_388_V_12_fu_930),
    .data_197_V_read(data_389_V_12_fu_934),
    .data_198_V_read(data_390_V_12_fu_938),
    .data_199_V_read(data_391_V_12_fu_942),
    .data_200_V_read(data_392_V_12_fu_946),
    .data_201_V_read(data_393_V_12_fu_950),
    .data_202_V_read(data_394_V_12_fu_954),
    .data_203_V_read(data_395_V_12_fu_958),
    .data_204_V_read(data_396_V_12_fu_962),
    .data_205_V_read(data_397_V_12_fu_966),
    .data_206_V_read(data_398_V_12_fu_970),
    .data_207_V_read(data_399_V_12_fu_974),
    .data_208_V_read(data_384_V_13_fu_978),
    .data_209_V_read(data_385_V_13_fu_982),
    .data_210_V_read(data_386_V_13_fu_986),
    .data_211_V_read(data_387_V_13_fu_990),
    .data_212_V_read(data_388_V_13_fu_994),
    .data_213_V_read(data_389_V_13_fu_998),
    .data_214_V_read(data_390_V_13_fu_1002),
    .data_215_V_read(data_391_V_13_fu_1006),
    .data_216_V_read(data_392_V_13_fu_1010),
    .data_217_V_read(data_393_V_13_fu_1014),
    .data_218_V_read(data_394_V_13_fu_1018),
    .data_219_V_read(data_395_V_13_fu_1022),
    .data_220_V_read(data_396_V_13_fu_1026),
    .data_221_V_read(data_397_V_13_fu_1030),
    .data_222_V_read(data_398_V_13_fu_1034),
    .data_223_V_read(data_399_V_13_fu_1038),
    .data_224_V_read(data_384_V_14_fu_1042),
    .data_225_V_read(data_385_V_14_fu_1046),
    .data_226_V_read(data_386_V_14_fu_1050),
    .data_227_V_read(data_387_V_14_fu_1054),
    .data_228_V_read(data_388_V_14_fu_1058),
    .data_229_V_read(data_389_V_14_fu_1062),
    .data_230_V_read(data_390_V_14_fu_1066),
    .data_231_V_read(data_391_V_14_fu_1070),
    .data_232_V_read(data_392_V_14_fu_1074),
    .data_233_V_read(data_393_V_14_fu_1078),
    .data_234_V_read(data_394_V_14_fu_1082),
    .data_235_V_read(data_395_V_14_fu_1086),
    .data_236_V_read(data_396_V_14_fu_1090),
    .data_237_V_read(data_397_V_14_fu_1094),
    .data_238_V_read(data_398_V_14_fu_1098),
    .data_239_V_read(data_399_V_14_fu_1102),
    .data_240_V_read(data_384_V_15_fu_1106),
    .data_241_V_read(data_385_V_15_fu_1110),
    .data_242_V_read(data_386_V_15_fu_1114),
    .data_243_V_read(data_387_V_15_fu_1118),
    .data_244_V_read(data_388_V_15_fu_1122),
    .data_245_V_read(data_389_V_15_fu_1126),
    .data_246_V_read(data_390_V_15_fu_1130),
    .data_247_V_read(data_391_V_15_fu_1134),
    .data_248_V_read(data_392_V_15_fu_1138),
    .data_249_V_read(data_393_V_15_fu_1142),
    .data_250_V_read(data_394_V_15_fu_1146),
    .data_251_V_read(data_395_V_15_fu_1150),
    .data_252_V_read(data_396_V_15_fu_1154),
    .data_253_V_read(data_397_V_15_fu_1158),
    .data_254_V_read(data_398_V_15_fu_1162),
    .data_255_V_read(data_399_V_15_fu_1166),
    .data_256_V_read(data_384_V_16_fu_1170),
    .data_257_V_read(data_385_V_16_fu_1174),
    .data_258_V_read(data_386_V_16_fu_1178),
    .data_259_V_read(data_387_V_16_fu_1182),
    .data_260_V_read(data_388_V_16_fu_1186),
    .data_261_V_read(data_389_V_16_fu_1190),
    .data_262_V_read(data_390_V_16_fu_1194),
    .data_263_V_read(data_391_V_16_fu_1198),
    .data_264_V_read(data_392_V_16_fu_1202),
    .data_265_V_read(data_393_V_16_fu_1206),
    .data_266_V_read(data_394_V_16_fu_1210),
    .data_267_V_read(data_395_V_16_fu_1214),
    .data_268_V_read(data_396_V_16_fu_1218),
    .data_269_V_read(data_397_V_16_fu_1222),
    .data_270_V_read(data_398_V_16_fu_1226),
    .data_271_V_read(data_399_V_16_fu_1230),
    .data_272_V_read(data_384_V_17_fu_1234),
    .data_273_V_read(data_385_V_17_fu_1238),
    .data_274_V_read(data_386_V_17_fu_1242),
    .data_275_V_read(data_387_V_17_fu_1246),
    .data_276_V_read(data_388_V_17_fu_1250),
    .data_277_V_read(data_389_V_17_fu_1254),
    .data_278_V_read(data_390_V_17_fu_1258),
    .data_279_V_read(data_391_V_17_fu_1262),
    .data_280_V_read(data_392_V_17_fu_1266),
    .data_281_V_read(data_393_V_17_fu_1270),
    .data_282_V_read(data_394_V_17_fu_1274),
    .data_283_V_read(data_395_V_17_fu_1278),
    .data_284_V_read(data_396_V_17_fu_1282),
    .data_285_V_read(data_397_V_17_fu_1286),
    .data_286_V_read(data_398_V_17_fu_1290),
    .data_287_V_read(data_399_V_17_fu_1294),
    .data_288_V_read(data_384_V_18_fu_1298),
    .data_289_V_read(data_385_V_18_fu_1302),
    .data_290_V_read(data_386_V_18_fu_1306),
    .data_291_V_read(data_387_V_18_fu_1310),
    .data_292_V_read(data_388_V_18_fu_1314),
    .data_293_V_read(data_389_V_18_fu_1318),
    .data_294_V_read(data_390_V_18_fu_1322),
    .data_295_V_read(data_391_V_18_fu_1326),
    .data_296_V_read(data_392_V_18_fu_1330),
    .data_297_V_read(data_393_V_18_fu_1334),
    .data_298_V_read(data_394_V_18_fu_1338),
    .data_299_V_read(data_395_V_18_fu_1342),
    .data_300_V_read(data_396_V_18_fu_1346),
    .data_301_V_read(data_397_V_18_fu_1350),
    .data_302_V_read(data_398_V_18_fu_1354),
    .data_303_V_read(data_399_V_18_fu_1358),
    .data_304_V_read(data_384_V_19_fu_1362),
    .data_305_V_read(data_385_V_19_fu_1366),
    .data_306_V_read(data_386_V_19_fu_1370),
    .data_307_V_read(data_387_V_19_fu_1374),
    .data_308_V_read(data_388_V_19_fu_1378),
    .data_309_V_read(data_389_V_19_fu_1382),
    .data_310_V_read(data_390_V_19_fu_1386),
    .data_311_V_read(data_391_V_19_fu_1390),
    .data_312_V_read(data_392_V_19_fu_1394),
    .data_313_V_read(data_393_V_19_fu_1398),
    .data_314_V_read(data_394_V_19_fu_1402),
    .data_315_V_read(data_395_V_19_fu_1406),
    .data_316_V_read(data_396_V_19_fu_1410),
    .data_317_V_read(data_397_V_19_fu_1414),
    .data_318_V_read(data_398_V_19_fu_1418),
    .data_319_V_read(data_399_V_19_fu_1422),
    .data_320_V_read(data_384_V_20_fu_1426),
    .data_321_V_read(data_385_V_20_fu_1430),
    .data_322_V_read(data_386_V_20_fu_1434),
    .data_323_V_read(data_387_V_20_fu_1438),
    .data_324_V_read(data_388_V_20_fu_1442),
    .data_325_V_read(data_389_V_20_fu_1446),
    .data_326_V_read(data_390_V_20_fu_1450),
    .data_327_V_read(data_391_V_20_fu_1454),
    .data_328_V_read(data_392_V_20_fu_1458),
    .data_329_V_read(data_393_V_20_fu_1462),
    .data_330_V_read(data_394_V_20_fu_1466),
    .data_331_V_read(data_395_V_20_fu_1470),
    .data_332_V_read(data_396_V_20_fu_1474),
    .data_333_V_read(data_397_V_20_fu_1478),
    .data_334_V_read(data_398_V_20_fu_1482),
    .data_335_V_read(data_399_V_20_fu_1486),
    .data_336_V_read(data_384_V_21_fu_1490),
    .data_337_V_read(data_385_V_21_fu_1494),
    .data_338_V_read(data_386_V_21_fu_1498),
    .data_339_V_read(data_387_V_21_fu_1502),
    .data_340_V_read(data_388_V_21_fu_1506),
    .data_341_V_read(data_389_V_21_fu_1510),
    .data_342_V_read(data_390_V_21_fu_1514),
    .data_343_V_read(data_391_V_21_fu_1518),
    .data_344_V_read(data_392_V_21_fu_1522),
    .data_345_V_read(data_393_V_21_fu_1526),
    .data_346_V_read(data_394_V_21_fu_1530),
    .data_347_V_read(data_395_V_21_fu_1534),
    .data_348_V_read(data_396_V_21_fu_1538),
    .data_349_V_read(data_397_V_21_fu_1542),
    .data_350_V_read(data_398_V_21_fu_1546),
    .data_351_V_read(data_399_V_21_fu_1550),
    .data_352_V_read(data_384_V_22_fu_1554),
    .data_353_V_read(data_385_V_22_fu_1558),
    .data_354_V_read(data_386_V_22_fu_1562),
    .data_355_V_read(data_387_V_22_fu_1566),
    .data_356_V_read(data_388_V_22_fu_1570),
    .data_357_V_read(data_389_V_22_fu_1574),
    .data_358_V_read(data_390_V_22_fu_1578),
    .data_359_V_read(data_391_V_22_fu_1582),
    .data_360_V_read(data_392_V_22_fu_1586),
    .data_361_V_read(data_393_V_22_fu_1590),
    .data_362_V_read(data_394_V_22_fu_1594),
    .data_363_V_read(data_395_V_22_fu_1598),
    .data_364_V_read(data_396_V_22_fu_1602),
    .data_365_V_read(data_397_V_22_fu_1606),
    .data_366_V_read(data_398_V_22_fu_1610),
    .data_367_V_read(data_399_V_22_fu_1614),
    .data_368_V_read(data_384_V_23_fu_1618),
    .data_369_V_read(data_385_V_23_fu_1622),
    .data_370_V_read(data_386_V_23_fu_1626),
    .data_371_V_read(data_387_V_23_fu_1630),
    .data_372_V_read(data_388_V_23_fu_1634),
    .data_373_V_read(data_389_V_23_fu_1638),
    .data_374_V_read(data_390_V_23_fu_1642),
    .data_375_V_read(data_391_V_23_fu_1646),
    .data_376_V_read(data_392_V_23_fu_1650),
    .data_377_V_read(data_393_V_23_fu_1654),
    .data_378_V_read(data_394_V_23_fu_1658),
    .data_379_V_read(data_395_V_23_fu_1662),
    .data_380_V_read(data_396_V_23_fu_1666),
    .data_381_V_read(data_397_V_23_fu_1670),
    .data_382_V_read(data_398_V_23_fu_1674),
    .data_383_V_read(data_399_V_23_fu_1678),
    .data_384_V_read(data_384_V_24_fu_1682),
    .data_385_V_read(data_385_V_24_fu_1686),
    .data_386_V_read(data_386_V_24_fu_1690),
    .data_387_V_read(data_387_V_24_fu_1694),
    .data_388_V_read(data_388_V_24_fu_1698),
    .data_389_V_read(data_389_V_24_fu_1702),
    .data_390_V_read(data_390_V_24_fu_1706),
    .data_391_V_read(data_391_V_24_fu_1710),
    .data_392_V_read(data_392_V_24_fu_1714),
    .data_393_V_read(data_393_V_24_fu_1718),
    .data_394_V_read(data_394_V_24_fu_1722),
    .data_395_V_read(data_395_V_24_fu_1726),
    .data_396_V_read(data_396_V_24_fu_1730),
    .data_397_V_read(data_397_V_24_fu_1734),
    .data_398_V_read(data_398_V_24_fu_1738),
    .data_399_V_read(data_399_V_24_fu_1742),
    .ap_return_0(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_0),
    .ap_return_1(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_1),
    .ap_return_2(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_2),
    .ap_return_3(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_3),
    .ap_return_4(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_4),
    .ap_return_5(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_5),
    .ap_return_6(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_6),
    .ap_return_7(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_7),
    .ap_return_8(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_8),
    .ap_return_9(grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg <= 1'b1;
        end else if ((grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_ready == 1'b1)) begin
            grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln41_reg_8350 == 1'd0))) begin
        i_in_0_reg_1816 <= i_in_reg_8354;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_in_0_reg_1816 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd10))) begin
        data_384_V_10_fu_786 <= data_stream_V_data_0_V_dout;
        data_385_V_10_fu_790 <= data_stream_V_data_1_V_dout;
        data_386_V_10_fu_794 <= data_stream_V_data_2_V_dout;
        data_387_V_10_fu_798 <= data_stream_V_data_3_V_dout;
        data_388_V_10_fu_802 <= data_stream_V_data_4_V_dout;
        data_389_V_10_fu_806 <= data_stream_V_data_5_V_dout;
        data_390_V_10_fu_810 <= data_stream_V_data_6_V_dout;
        data_391_V_10_fu_814 <= data_stream_V_data_7_V_dout;
        data_392_V_10_fu_818 <= data_stream_V_data_8_V_dout;
        data_393_V_10_fu_822 <= data_stream_V_data_9_V_dout;
        data_394_V_10_fu_826 <= data_stream_V_data_10_V_dout;
        data_395_V_10_fu_830 <= data_stream_V_data_11_V_dout;
        data_396_V_10_fu_834 <= data_stream_V_data_12_V_dout;
        data_397_V_10_fu_838 <= data_stream_V_data_13_V_dout;
        data_398_V_10_fu_842 <= data_stream_V_data_14_V_dout;
        data_399_V_10_fu_846 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd11))) begin
        data_384_V_11_fu_850 <= data_stream_V_data_0_V_dout;
        data_385_V_11_fu_854 <= data_stream_V_data_1_V_dout;
        data_386_V_11_fu_858 <= data_stream_V_data_2_V_dout;
        data_387_V_11_fu_862 <= data_stream_V_data_3_V_dout;
        data_388_V_11_fu_866 <= data_stream_V_data_4_V_dout;
        data_389_V_11_fu_870 <= data_stream_V_data_5_V_dout;
        data_390_V_11_fu_874 <= data_stream_V_data_6_V_dout;
        data_391_V_11_fu_878 <= data_stream_V_data_7_V_dout;
        data_392_V_11_fu_882 <= data_stream_V_data_8_V_dout;
        data_393_V_11_fu_886 <= data_stream_V_data_9_V_dout;
        data_394_V_11_fu_890 <= data_stream_V_data_10_V_dout;
        data_395_V_11_fu_894 <= data_stream_V_data_11_V_dout;
        data_396_V_11_fu_898 <= data_stream_V_data_12_V_dout;
        data_397_V_11_fu_902 <= data_stream_V_data_13_V_dout;
        data_398_V_11_fu_906 <= data_stream_V_data_14_V_dout;
        data_399_V_11_fu_910 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd12))) begin
        data_384_V_12_fu_914 <= data_stream_V_data_0_V_dout;
        data_385_V_12_fu_918 <= data_stream_V_data_1_V_dout;
        data_386_V_12_fu_922 <= data_stream_V_data_2_V_dout;
        data_387_V_12_fu_926 <= data_stream_V_data_3_V_dout;
        data_388_V_12_fu_930 <= data_stream_V_data_4_V_dout;
        data_389_V_12_fu_934 <= data_stream_V_data_5_V_dout;
        data_390_V_12_fu_938 <= data_stream_V_data_6_V_dout;
        data_391_V_12_fu_942 <= data_stream_V_data_7_V_dout;
        data_392_V_12_fu_946 <= data_stream_V_data_8_V_dout;
        data_393_V_12_fu_950 <= data_stream_V_data_9_V_dout;
        data_394_V_12_fu_954 <= data_stream_V_data_10_V_dout;
        data_395_V_12_fu_958 <= data_stream_V_data_11_V_dout;
        data_396_V_12_fu_962 <= data_stream_V_data_12_V_dout;
        data_397_V_12_fu_966 <= data_stream_V_data_13_V_dout;
        data_398_V_12_fu_970 <= data_stream_V_data_14_V_dout;
        data_399_V_12_fu_974 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd13))) begin
        data_384_V_13_fu_978 <= data_stream_V_data_0_V_dout;
        data_385_V_13_fu_982 <= data_stream_V_data_1_V_dout;
        data_386_V_13_fu_986 <= data_stream_V_data_2_V_dout;
        data_387_V_13_fu_990 <= data_stream_V_data_3_V_dout;
        data_388_V_13_fu_994 <= data_stream_V_data_4_V_dout;
        data_389_V_13_fu_998 <= data_stream_V_data_5_V_dout;
        data_390_V_13_fu_1002 <= data_stream_V_data_6_V_dout;
        data_391_V_13_fu_1006 <= data_stream_V_data_7_V_dout;
        data_392_V_13_fu_1010 <= data_stream_V_data_8_V_dout;
        data_393_V_13_fu_1014 <= data_stream_V_data_9_V_dout;
        data_394_V_13_fu_1018 <= data_stream_V_data_10_V_dout;
        data_395_V_13_fu_1022 <= data_stream_V_data_11_V_dout;
        data_396_V_13_fu_1026 <= data_stream_V_data_12_V_dout;
        data_397_V_13_fu_1030 <= data_stream_V_data_13_V_dout;
        data_398_V_13_fu_1034 <= data_stream_V_data_14_V_dout;
        data_399_V_13_fu_1038 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd14))) begin
        data_384_V_14_fu_1042 <= data_stream_V_data_0_V_dout;
        data_385_V_14_fu_1046 <= data_stream_V_data_1_V_dout;
        data_386_V_14_fu_1050 <= data_stream_V_data_2_V_dout;
        data_387_V_14_fu_1054 <= data_stream_V_data_3_V_dout;
        data_388_V_14_fu_1058 <= data_stream_V_data_4_V_dout;
        data_389_V_14_fu_1062 <= data_stream_V_data_5_V_dout;
        data_390_V_14_fu_1066 <= data_stream_V_data_6_V_dout;
        data_391_V_14_fu_1070 <= data_stream_V_data_7_V_dout;
        data_392_V_14_fu_1074 <= data_stream_V_data_8_V_dout;
        data_393_V_14_fu_1078 <= data_stream_V_data_9_V_dout;
        data_394_V_14_fu_1082 <= data_stream_V_data_10_V_dout;
        data_395_V_14_fu_1086 <= data_stream_V_data_11_V_dout;
        data_396_V_14_fu_1090 <= data_stream_V_data_12_V_dout;
        data_397_V_14_fu_1094 <= data_stream_V_data_13_V_dout;
        data_398_V_14_fu_1098 <= data_stream_V_data_14_V_dout;
        data_399_V_14_fu_1102 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd15))) begin
        data_384_V_15_fu_1106 <= data_stream_V_data_0_V_dout;
        data_385_V_15_fu_1110 <= data_stream_V_data_1_V_dout;
        data_386_V_15_fu_1114 <= data_stream_V_data_2_V_dout;
        data_387_V_15_fu_1118 <= data_stream_V_data_3_V_dout;
        data_388_V_15_fu_1122 <= data_stream_V_data_4_V_dout;
        data_389_V_15_fu_1126 <= data_stream_V_data_5_V_dout;
        data_390_V_15_fu_1130 <= data_stream_V_data_6_V_dout;
        data_391_V_15_fu_1134 <= data_stream_V_data_7_V_dout;
        data_392_V_15_fu_1138 <= data_stream_V_data_8_V_dout;
        data_393_V_15_fu_1142 <= data_stream_V_data_9_V_dout;
        data_394_V_15_fu_1146 <= data_stream_V_data_10_V_dout;
        data_395_V_15_fu_1150 <= data_stream_V_data_11_V_dout;
        data_396_V_15_fu_1154 <= data_stream_V_data_12_V_dout;
        data_397_V_15_fu_1158 <= data_stream_V_data_13_V_dout;
        data_398_V_15_fu_1162 <= data_stream_V_data_14_V_dout;
        data_399_V_15_fu_1166 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd16))) begin
        data_384_V_16_fu_1170 <= data_stream_V_data_0_V_dout;
        data_385_V_16_fu_1174 <= data_stream_V_data_1_V_dout;
        data_386_V_16_fu_1178 <= data_stream_V_data_2_V_dout;
        data_387_V_16_fu_1182 <= data_stream_V_data_3_V_dout;
        data_388_V_16_fu_1186 <= data_stream_V_data_4_V_dout;
        data_389_V_16_fu_1190 <= data_stream_V_data_5_V_dout;
        data_390_V_16_fu_1194 <= data_stream_V_data_6_V_dout;
        data_391_V_16_fu_1198 <= data_stream_V_data_7_V_dout;
        data_392_V_16_fu_1202 <= data_stream_V_data_8_V_dout;
        data_393_V_16_fu_1206 <= data_stream_V_data_9_V_dout;
        data_394_V_16_fu_1210 <= data_stream_V_data_10_V_dout;
        data_395_V_16_fu_1214 <= data_stream_V_data_11_V_dout;
        data_396_V_16_fu_1218 <= data_stream_V_data_12_V_dout;
        data_397_V_16_fu_1222 <= data_stream_V_data_13_V_dout;
        data_398_V_16_fu_1226 <= data_stream_V_data_14_V_dout;
        data_399_V_16_fu_1230 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd17))) begin
        data_384_V_17_fu_1234 <= data_stream_V_data_0_V_dout;
        data_385_V_17_fu_1238 <= data_stream_V_data_1_V_dout;
        data_386_V_17_fu_1242 <= data_stream_V_data_2_V_dout;
        data_387_V_17_fu_1246 <= data_stream_V_data_3_V_dout;
        data_388_V_17_fu_1250 <= data_stream_V_data_4_V_dout;
        data_389_V_17_fu_1254 <= data_stream_V_data_5_V_dout;
        data_390_V_17_fu_1258 <= data_stream_V_data_6_V_dout;
        data_391_V_17_fu_1262 <= data_stream_V_data_7_V_dout;
        data_392_V_17_fu_1266 <= data_stream_V_data_8_V_dout;
        data_393_V_17_fu_1270 <= data_stream_V_data_9_V_dout;
        data_394_V_17_fu_1274 <= data_stream_V_data_10_V_dout;
        data_395_V_17_fu_1278 <= data_stream_V_data_11_V_dout;
        data_396_V_17_fu_1282 <= data_stream_V_data_12_V_dout;
        data_397_V_17_fu_1286 <= data_stream_V_data_13_V_dout;
        data_398_V_17_fu_1290 <= data_stream_V_data_14_V_dout;
        data_399_V_17_fu_1294 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd18))) begin
        data_384_V_18_fu_1298 <= data_stream_V_data_0_V_dout;
        data_385_V_18_fu_1302 <= data_stream_V_data_1_V_dout;
        data_386_V_18_fu_1306 <= data_stream_V_data_2_V_dout;
        data_387_V_18_fu_1310 <= data_stream_V_data_3_V_dout;
        data_388_V_18_fu_1314 <= data_stream_V_data_4_V_dout;
        data_389_V_18_fu_1318 <= data_stream_V_data_5_V_dout;
        data_390_V_18_fu_1322 <= data_stream_V_data_6_V_dout;
        data_391_V_18_fu_1326 <= data_stream_V_data_7_V_dout;
        data_392_V_18_fu_1330 <= data_stream_V_data_8_V_dout;
        data_393_V_18_fu_1334 <= data_stream_V_data_9_V_dout;
        data_394_V_18_fu_1338 <= data_stream_V_data_10_V_dout;
        data_395_V_18_fu_1342 <= data_stream_V_data_11_V_dout;
        data_396_V_18_fu_1346 <= data_stream_V_data_12_V_dout;
        data_397_V_18_fu_1350 <= data_stream_V_data_13_V_dout;
        data_398_V_18_fu_1354 <= data_stream_V_data_14_V_dout;
        data_399_V_18_fu_1358 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd19))) begin
        data_384_V_19_fu_1362 <= data_stream_V_data_0_V_dout;
        data_385_V_19_fu_1366 <= data_stream_V_data_1_V_dout;
        data_386_V_19_fu_1370 <= data_stream_V_data_2_V_dout;
        data_387_V_19_fu_1374 <= data_stream_V_data_3_V_dout;
        data_388_V_19_fu_1378 <= data_stream_V_data_4_V_dout;
        data_389_V_19_fu_1382 <= data_stream_V_data_5_V_dout;
        data_390_V_19_fu_1386 <= data_stream_V_data_6_V_dout;
        data_391_V_19_fu_1390 <= data_stream_V_data_7_V_dout;
        data_392_V_19_fu_1394 <= data_stream_V_data_8_V_dout;
        data_393_V_19_fu_1398 <= data_stream_V_data_9_V_dout;
        data_394_V_19_fu_1402 <= data_stream_V_data_10_V_dout;
        data_395_V_19_fu_1406 <= data_stream_V_data_11_V_dout;
        data_396_V_19_fu_1410 <= data_stream_V_data_12_V_dout;
        data_397_V_19_fu_1414 <= data_stream_V_data_13_V_dout;
        data_398_V_19_fu_1418 <= data_stream_V_data_14_V_dout;
        data_399_V_19_fu_1422 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd1))) begin
        data_384_V_1_fu_210 <= data_stream_V_data_0_V_dout;
        data_385_V_1_fu_214 <= data_stream_V_data_1_V_dout;
        data_386_V_1_fu_218 <= data_stream_V_data_2_V_dout;
        data_387_V_1_fu_222 <= data_stream_V_data_3_V_dout;
        data_388_V_1_fu_226 <= data_stream_V_data_4_V_dout;
        data_389_V_1_fu_230 <= data_stream_V_data_5_V_dout;
        data_390_V_1_fu_234 <= data_stream_V_data_6_V_dout;
        data_391_V_1_fu_238 <= data_stream_V_data_7_V_dout;
        data_392_V_1_fu_242 <= data_stream_V_data_8_V_dout;
        data_393_V_1_fu_246 <= data_stream_V_data_9_V_dout;
        data_394_V_1_fu_250 <= data_stream_V_data_10_V_dout;
        data_395_V_1_fu_254 <= data_stream_V_data_11_V_dout;
        data_396_V_1_fu_258 <= data_stream_V_data_12_V_dout;
        data_397_V_1_fu_262 <= data_stream_V_data_13_V_dout;
        data_398_V_1_fu_266 <= data_stream_V_data_14_V_dout;
        data_399_V_1_fu_270 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd20))) begin
        data_384_V_20_fu_1426 <= data_stream_V_data_0_V_dout;
        data_385_V_20_fu_1430 <= data_stream_V_data_1_V_dout;
        data_386_V_20_fu_1434 <= data_stream_V_data_2_V_dout;
        data_387_V_20_fu_1438 <= data_stream_V_data_3_V_dout;
        data_388_V_20_fu_1442 <= data_stream_V_data_4_V_dout;
        data_389_V_20_fu_1446 <= data_stream_V_data_5_V_dout;
        data_390_V_20_fu_1450 <= data_stream_V_data_6_V_dout;
        data_391_V_20_fu_1454 <= data_stream_V_data_7_V_dout;
        data_392_V_20_fu_1458 <= data_stream_V_data_8_V_dout;
        data_393_V_20_fu_1462 <= data_stream_V_data_9_V_dout;
        data_394_V_20_fu_1466 <= data_stream_V_data_10_V_dout;
        data_395_V_20_fu_1470 <= data_stream_V_data_11_V_dout;
        data_396_V_20_fu_1474 <= data_stream_V_data_12_V_dout;
        data_397_V_20_fu_1478 <= data_stream_V_data_13_V_dout;
        data_398_V_20_fu_1482 <= data_stream_V_data_14_V_dout;
        data_399_V_20_fu_1486 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd21))) begin
        data_384_V_21_fu_1490 <= data_stream_V_data_0_V_dout;
        data_385_V_21_fu_1494 <= data_stream_V_data_1_V_dout;
        data_386_V_21_fu_1498 <= data_stream_V_data_2_V_dout;
        data_387_V_21_fu_1502 <= data_stream_V_data_3_V_dout;
        data_388_V_21_fu_1506 <= data_stream_V_data_4_V_dout;
        data_389_V_21_fu_1510 <= data_stream_V_data_5_V_dout;
        data_390_V_21_fu_1514 <= data_stream_V_data_6_V_dout;
        data_391_V_21_fu_1518 <= data_stream_V_data_7_V_dout;
        data_392_V_21_fu_1522 <= data_stream_V_data_8_V_dout;
        data_393_V_21_fu_1526 <= data_stream_V_data_9_V_dout;
        data_394_V_21_fu_1530 <= data_stream_V_data_10_V_dout;
        data_395_V_21_fu_1534 <= data_stream_V_data_11_V_dout;
        data_396_V_21_fu_1538 <= data_stream_V_data_12_V_dout;
        data_397_V_21_fu_1542 <= data_stream_V_data_13_V_dout;
        data_398_V_21_fu_1546 <= data_stream_V_data_14_V_dout;
        data_399_V_21_fu_1550 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd22))) begin
        data_384_V_22_fu_1554 <= data_stream_V_data_0_V_dout;
        data_385_V_22_fu_1558 <= data_stream_V_data_1_V_dout;
        data_386_V_22_fu_1562 <= data_stream_V_data_2_V_dout;
        data_387_V_22_fu_1566 <= data_stream_V_data_3_V_dout;
        data_388_V_22_fu_1570 <= data_stream_V_data_4_V_dout;
        data_389_V_22_fu_1574 <= data_stream_V_data_5_V_dout;
        data_390_V_22_fu_1578 <= data_stream_V_data_6_V_dout;
        data_391_V_22_fu_1582 <= data_stream_V_data_7_V_dout;
        data_392_V_22_fu_1586 <= data_stream_V_data_8_V_dout;
        data_393_V_22_fu_1590 <= data_stream_V_data_9_V_dout;
        data_394_V_22_fu_1594 <= data_stream_V_data_10_V_dout;
        data_395_V_22_fu_1598 <= data_stream_V_data_11_V_dout;
        data_396_V_22_fu_1602 <= data_stream_V_data_12_V_dout;
        data_397_V_22_fu_1606 <= data_stream_V_data_13_V_dout;
        data_398_V_22_fu_1610 <= data_stream_V_data_14_V_dout;
        data_399_V_22_fu_1614 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd23))) begin
        data_384_V_23_fu_1618 <= data_stream_V_data_0_V_dout;
        data_385_V_23_fu_1622 <= data_stream_V_data_1_V_dout;
        data_386_V_23_fu_1626 <= data_stream_V_data_2_V_dout;
        data_387_V_23_fu_1630 <= data_stream_V_data_3_V_dout;
        data_388_V_23_fu_1634 <= data_stream_V_data_4_V_dout;
        data_389_V_23_fu_1638 <= data_stream_V_data_5_V_dout;
        data_390_V_23_fu_1642 <= data_stream_V_data_6_V_dout;
        data_391_V_23_fu_1646 <= data_stream_V_data_7_V_dout;
        data_392_V_23_fu_1650 <= data_stream_V_data_8_V_dout;
        data_393_V_23_fu_1654 <= data_stream_V_data_9_V_dout;
        data_394_V_23_fu_1658 <= data_stream_V_data_10_V_dout;
        data_395_V_23_fu_1662 <= data_stream_V_data_11_V_dout;
        data_396_V_23_fu_1666 <= data_stream_V_data_12_V_dout;
        data_397_V_23_fu_1670 <= data_stream_V_data_13_V_dout;
        data_398_V_23_fu_1674 <= data_stream_V_data_14_V_dout;
        data_399_V_23_fu_1678 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((i_in_0_reg_1816 == 5'd24) | ((i_in_0_reg_1816 == 5'd25) | ((i_in_0_reg_1816 == 5'd26) | ((i_in_0_reg_1816 == 5'd27) | ((i_in_0_reg_1816 == 5'd28) | ((i_in_0_reg_1816 == 5'd29) | ((i_in_0_reg_1816 == 5'd30) | (i_in_0_reg_1816 == 5'd31)))))))))) begin
        data_384_V_24_fu_1682 <= data_stream_V_data_0_V_dout;
        data_385_V_24_fu_1686 <= data_stream_V_data_1_V_dout;
        data_386_V_24_fu_1690 <= data_stream_V_data_2_V_dout;
        data_387_V_24_fu_1694 <= data_stream_V_data_3_V_dout;
        data_388_V_24_fu_1698 <= data_stream_V_data_4_V_dout;
        data_389_V_24_fu_1702 <= data_stream_V_data_5_V_dout;
        data_390_V_24_fu_1706 <= data_stream_V_data_6_V_dout;
        data_391_V_24_fu_1710 <= data_stream_V_data_7_V_dout;
        data_392_V_24_fu_1714 <= data_stream_V_data_8_V_dout;
        data_393_V_24_fu_1718 <= data_stream_V_data_9_V_dout;
        data_394_V_24_fu_1722 <= data_stream_V_data_10_V_dout;
        data_395_V_24_fu_1726 <= data_stream_V_data_11_V_dout;
        data_396_V_24_fu_1730 <= data_stream_V_data_12_V_dout;
        data_397_V_24_fu_1734 <= data_stream_V_data_13_V_dout;
        data_398_V_24_fu_1738 <= data_stream_V_data_14_V_dout;
        data_399_V_24_fu_1742 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd2))) begin
        data_384_V_2_fu_274 <= data_stream_V_data_0_V_dout;
        data_385_V_2_fu_278 <= data_stream_V_data_1_V_dout;
        data_386_V_2_fu_282 <= data_stream_V_data_2_V_dout;
        data_387_V_2_fu_286 <= data_stream_V_data_3_V_dout;
        data_388_V_2_fu_290 <= data_stream_V_data_4_V_dout;
        data_389_V_2_fu_294 <= data_stream_V_data_5_V_dout;
        data_390_V_2_fu_298 <= data_stream_V_data_6_V_dout;
        data_391_V_2_fu_302 <= data_stream_V_data_7_V_dout;
        data_392_V_2_fu_306 <= data_stream_V_data_8_V_dout;
        data_393_V_2_fu_310 <= data_stream_V_data_9_V_dout;
        data_394_V_2_fu_314 <= data_stream_V_data_10_V_dout;
        data_395_V_2_fu_318 <= data_stream_V_data_11_V_dout;
        data_396_V_2_fu_322 <= data_stream_V_data_12_V_dout;
        data_397_V_2_fu_326 <= data_stream_V_data_13_V_dout;
        data_398_V_2_fu_330 <= data_stream_V_data_14_V_dout;
        data_399_V_2_fu_334 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd3))) begin
        data_384_V_3_fu_338 <= data_stream_V_data_0_V_dout;
        data_385_V_3_fu_342 <= data_stream_V_data_1_V_dout;
        data_386_V_3_fu_346 <= data_stream_V_data_2_V_dout;
        data_387_V_3_fu_350 <= data_stream_V_data_3_V_dout;
        data_388_V_3_fu_354 <= data_stream_V_data_4_V_dout;
        data_389_V_3_fu_358 <= data_stream_V_data_5_V_dout;
        data_390_V_3_fu_362 <= data_stream_V_data_6_V_dout;
        data_391_V_3_fu_366 <= data_stream_V_data_7_V_dout;
        data_392_V_3_fu_370 <= data_stream_V_data_8_V_dout;
        data_393_V_3_fu_374 <= data_stream_V_data_9_V_dout;
        data_394_V_3_fu_378 <= data_stream_V_data_10_V_dout;
        data_395_V_3_fu_382 <= data_stream_V_data_11_V_dout;
        data_396_V_3_fu_386 <= data_stream_V_data_12_V_dout;
        data_397_V_3_fu_390 <= data_stream_V_data_13_V_dout;
        data_398_V_3_fu_394 <= data_stream_V_data_14_V_dout;
        data_399_V_3_fu_398 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd4))) begin
        data_384_V_4_fu_402 <= data_stream_V_data_0_V_dout;
        data_385_V_4_fu_406 <= data_stream_V_data_1_V_dout;
        data_386_V_4_fu_410 <= data_stream_V_data_2_V_dout;
        data_387_V_4_fu_414 <= data_stream_V_data_3_V_dout;
        data_388_V_4_fu_418 <= data_stream_V_data_4_V_dout;
        data_389_V_4_fu_422 <= data_stream_V_data_5_V_dout;
        data_390_V_4_fu_426 <= data_stream_V_data_6_V_dout;
        data_391_V_4_fu_430 <= data_stream_V_data_7_V_dout;
        data_392_V_4_fu_434 <= data_stream_V_data_8_V_dout;
        data_393_V_4_fu_438 <= data_stream_V_data_9_V_dout;
        data_394_V_4_fu_442 <= data_stream_V_data_10_V_dout;
        data_395_V_4_fu_446 <= data_stream_V_data_11_V_dout;
        data_396_V_4_fu_450 <= data_stream_V_data_12_V_dout;
        data_397_V_4_fu_454 <= data_stream_V_data_13_V_dout;
        data_398_V_4_fu_458 <= data_stream_V_data_14_V_dout;
        data_399_V_4_fu_462 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd5))) begin
        data_384_V_5_fu_466 <= data_stream_V_data_0_V_dout;
        data_385_V_5_fu_470 <= data_stream_V_data_1_V_dout;
        data_386_V_5_fu_474 <= data_stream_V_data_2_V_dout;
        data_387_V_5_fu_478 <= data_stream_V_data_3_V_dout;
        data_388_V_5_fu_482 <= data_stream_V_data_4_V_dout;
        data_389_V_5_fu_486 <= data_stream_V_data_5_V_dout;
        data_390_V_5_fu_490 <= data_stream_V_data_6_V_dout;
        data_391_V_5_fu_494 <= data_stream_V_data_7_V_dout;
        data_392_V_5_fu_498 <= data_stream_V_data_8_V_dout;
        data_393_V_5_fu_502 <= data_stream_V_data_9_V_dout;
        data_394_V_5_fu_506 <= data_stream_V_data_10_V_dout;
        data_395_V_5_fu_510 <= data_stream_V_data_11_V_dout;
        data_396_V_5_fu_514 <= data_stream_V_data_12_V_dout;
        data_397_V_5_fu_518 <= data_stream_V_data_13_V_dout;
        data_398_V_5_fu_522 <= data_stream_V_data_14_V_dout;
        data_399_V_5_fu_526 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd6))) begin
        data_384_V_6_fu_530 <= data_stream_V_data_0_V_dout;
        data_385_V_6_fu_534 <= data_stream_V_data_1_V_dout;
        data_386_V_6_fu_538 <= data_stream_V_data_2_V_dout;
        data_387_V_6_fu_542 <= data_stream_V_data_3_V_dout;
        data_388_V_6_fu_546 <= data_stream_V_data_4_V_dout;
        data_389_V_6_fu_550 <= data_stream_V_data_5_V_dout;
        data_390_V_6_fu_554 <= data_stream_V_data_6_V_dout;
        data_391_V_6_fu_558 <= data_stream_V_data_7_V_dout;
        data_392_V_6_fu_562 <= data_stream_V_data_8_V_dout;
        data_393_V_6_fu_566 <= data_stream_V_data_9_V_dout;
        data_394_V_6_fu_570 <= data_stream_V_data_10_V_dout;
        data_395_V_6_fu_574 <= data_stream_V_data_11_V_dout;
        data_396_V_6_fu_578 <= data_stream_V_data_12_V_dout;
        data_397_V_6_fu_582 <= data_stream_V_data_13_V_dout;
        data_398_V_6_fu_586 <= data_stream_V_data_14_V_dout;
        data_399_V_6_fu_590 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd7))) begin
        data_384_V_7_fu_594 <= data_stream_V_data_0_V_dout;
        data_385_V_7_fu_598 <= data_stream_V_data_1_V_dout;
        data_386_V_7_fu_602 <= data_stream_V_data_2_V_dout;
        data_387_V_7_fu_606 <= data_stream_V_data_3_V_dout;
        data_388_V_7_fu_610 <= data_stream_V_data_4_V_dout;
        data_389_V_7_fu_614 <= data_stream_V_data_5_V_dout;
        data_390_V_7_fu_618 <= data_stream_V_data_6_V_dout;
        data_391_V_7_fu_622 <= data_stream_V_data_7_V_dout;
        data_392_V_7_fu_626 <= data_stream_V_data_8_V_dout;
        data_393_V_7_fu_630 <= data_stream_V_data_9_V_dout;
        data_394_V_7_fu_634 <= data_stream_V_data_10_V_dout;
        data_395_V_7_fu_638 <= data_stream_V_data_11_V_dout;
        data_396_V_7_fu_642 <= data_stream_V_data_12_V_dout;
        data_397_V_7_fu_646 <= data_stream_V_data_13_V_dout;
        data_398_V_7_fu_650 <= data_stream_V_data_14_V_dout;
        data_399_V_7_fu_654 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd8))) begin
        data_384_V_8_fu_658 <= data_stream_V_data_0_V_dout;
        data_385_V_8_fu_662 <= data_stream_V_data_1_V_dout;
        data_386_V_8_fu_666 <= data_stream_V_data_2_V_dout;
        data_387_V_8_fu_670 <= data_stream_V_data_3_V_dout;
        data_388_V_8_fu_674 <= data_stream_V_data_4_V_dout;
        data_389_V_8_fu_678 <= data_stream_V_data_5_V_dout;
        data_390_V_8_fu_682 <= data_stream_V_data_6_V_dout;
        data_391_V_8_fu_686 <= data_stream_V_data_7_V_dout;
        data_392_V_8_fu_690 <= data_stream_V_data_8_V_dout;
        data_393_V_8_fu_694 <= data_stream_V_data_9_V_dout;
        data_394_V_8_fu_698 <= data_stream_V_data_10_V_dout;
        data_395_V_8_fu_702 <= data_stream_V_data_11_V_dout;
        data_396_V_8_fu_706 <= data_stream_V_data_12_V_dout;
        data_397_V_8_fu_710 <= data_stream_V_data_13_V_dout;
        data_398_V_8_fu_714 <= data_stream_V_data_14_V_dout;
        data_399_V_8_fu_718 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd9))) begin
        data_384_V_9_fu_722 <= data_stream_V_data_0_V_dout;
        data_385_V_9_fu_726 <= data_stream_V_data_1_V_dout;
        data_386_V_9_fu_730 <= data_stream_V_data_2_V_dout;
        data_387_V_9_fu_734 <= data_stream_V_data_3_V_dout;
        data_388_V_9_fu_738 <= data_stream_V_data_4_V_dout;
        data_389_V_9_fu_742 <= data_stream_V_data_5_V_dout;
        data_390_V_9_fu_746 <= data_stream_V_data_6_V_dout;
        data_391_V_9_fu_750 <= data_stream_V_data_7_V_dout;
        data_392_V_9_fu_754 <= data_stream_V_data_8_V_dout;
        data_393_V_9_fu_758 <= data_stream_V_data_9_V_dout;
        data_394_V_9_fu_762 <= data_stream_V_data_10_V_dout;
        data_395_V_9_fu_766 <= data_stream_V_data_11_V_dout;
        data_396_V_9_fu_770 <= data_stream_V_data_12_V_dout;
        data_397_V_9_fu_774 <= data_stream_V_data_13_V_dout;
        data_398_V_9_fu_778 <= data_stream_V_data_14_V_dout;
        data_399_V_9_fu_782 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (i_in_0_reg_1816 == 5'd0))) begin
        data_384_V_fu_146 <= data_stream_V_data_0_V_dout;
        data_385_V_fu_150 <= data_stream_V_data_1_V_dout;
        data_386_V_fu_154 <= data_stream_V_data_2_V_dout;
        data_387_V_fu_158 <= data_stream_V_data_3_V_dout;
        data_388_V_fu_162 <= data_stream_V_data_4_V_dout;
        data_389_V_fu_166 <= data_stream_V_data_5_V_dout;
        data_390_V_fu_170 <= data_stream_V_data_6_V_dout;
        data_391_V_fu_174 <= data_stream_V_data_7_V_dout;
        data_392_V_fu_178 <= data_stream_V_data_8_V_dout;
        data_393_V_fu_182 <= data_stream_V_data_9_V_dout;
        data_394_V_fu_186 <= data_stream_V_data_10_V_dout;
        data_395_V_fu_190 <= data_stream_V_data_11_V_dout;
        data_396_V_fu_194 <= data_stream_V_data_12_V_dout;
        data_397_V_fu_198 <= data_stream_V_data_13_V_dout;
        data_398_V_fu_202 <= data_stream_V_data_14_V_dout;
        data_399_V_fu_206 <= data_stream_V_data_15_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_in_reg_8354 <= i_in_fu_2240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln41_reg_8350 <= icmp_ln41_fu_2234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_done == 1'b1))) begin
        tmp_data_0_V_reg_10359 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_0;
        tmp_data_1_V_reg_10364 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_1;
        tmp_data_2_V_reg_10369 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_2;
        tmp_data_3_V_reg_10374 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_3;
        tmp_data_4_V_reg_10379 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_4;
        tmp_data_5_V_reg_10384 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_5;
        tmp_data_6_V_reg_10389 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_6;
        tmp_data_7_V_reg_10394 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_7;
        tmp_data_8_V_reg_10399 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_8;
        tmp_data_9_V_reg_10404 <= grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_return_9;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_2234_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln41_reg_8350 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i_in_0_phi_fu_1820_p4 = i_in_reg_8354;
    end else begin
        ap_phi_mux_i_in_0_phi_fu_1820_p4 = i_in_0_reg_1816;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_0_V_blk_n = data_stream_V_data_0_V_empty_n;
    end else begin
        data_stream_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_0_V_read = 1'b1;
    end else begin
        data_stream_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_10_V_blk_n = data_stream_V_data_10_V_empty_n;
    end else begin
        data_stream_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_10_V_read = 1'b1;
    end else begin
        data_stream_V_data_10_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_11_V_blk_n = data_stream_V_data_11_V_empty_n;
    end else begin
        data_stream_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_11_V_read = 1'b1;
    end else begin
        data_stream_V_data_11_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_12_V_blk_n = data_stream_V_data_12_V_empty_n;
    end else begin
        data_stream_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_12_V_read = 1'b1;
    end else begin
        data_stream_V_data_12_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_13_V_blk_n = data_stream_V_data_13_V_empty_n;
    end else begin
        data_stream_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_13_V_read = 1'b1;
    end else begin
        data_stream_V_data_13_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_14_V_blk_n = data_stream_V_data_14_V_empty_n;
    end else begin
        data_stream_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_14_V_read = 1'b1;
    end else begin
        data_stream_V_data_14_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_15_V_blk_n = data_stream_V_data_15_V_empty_n;
    end else begin
        data_stream_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_15_V_read = 1'b1;
    end else begin
        data_stream_V_data_15_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_1_V_blk_n = data_stream_V_data_1_V_empty_n;
    end else begin
        data_stream_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_1_V_read = 1'b1;
    end else begin
        data_stream_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_2_V_blk_n = data_stream_V_data_2_V_empty_n;
    end else begin
        data_stream_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_2_V_read = 1'b1;
    end else begin
        data_stream_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_3_V_blk_n = data_stream_V_data_3_V_empty_n;
    end else begin
        data_stream_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_3_V_read = 1'b1;
    end else begin
        data_stream_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_4_V_blk_n = data_stream_V_data_4_V_empty_n;
    end else begin
        data_stream_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_4_V_read = 1'b1;
    end else begin
        data_stream_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_5_V_blk_n = data_stream_V_data_5_V_empty_n;
    end else begin
        data_stream_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_5_V_read = 1'b1;
    end else begin
        data_stream_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_6_V_blk_n = data_stream_V_data_6_V_empty_n;
    end else begin
        data_stream_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_6_V_read = 1'b1;
    end else begin
        data_stream_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_7_V_blk_n = data_stream_V_data_7_V_empty_n;
    end else begin
        data_stream_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_7_V_read = 1'b1;
    end else begin
        data_stream_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_8_V_blk_n = data_stream_V_data_8_V_empty_n;
    end else begin
        data_stream_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_8_V_read = 1'b1;
    end else begin
        data_stream_V_data_8_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_stream_V_data_9_V_blk_n = data_stream_V_data_9_V_empty_n;
    end else begin
        data_stream_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_stream_V_data_9_V_read = 1'b1;
    end else begin
        data_stream_V_data_9_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_0_V_blk_n = res_stream_V_data_0_V_full_n;
    end else begin
        res_stream_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_0_V_write = 1'b1;
    end else begin
        res_stream_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_1_V_blk_n = res_stream_V_data_1_V_full_n;
    end else begin
        res_stream_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_1_V_write = 1'b1;
    end else begin
        res_stream_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_2_V_blk_n = res_stream_V_data_2_V_full_n;
    end else begin
        res_stream_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_2_V_write = 1'b1;
    end else begin
        res_stream_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_3_V_blk_n = res_stream_V_data_3_V_full_n;
    end else begin
        res_stream_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_3_V_write = 1'b1;
    end else begin
        res_stream_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_4_V_blk_n = res_stream_V_data_4_V_full_n;
    end else begin
        res_stream_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_4_V_write = 1'b1;
    end else begin
        res_stream_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_5_V_blk_n = res_stream_V_data_5_V_full_n;
    end else begin
        res_stream_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_5_V_write = 1'b1;
    end else begin
        res_stream_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_6_V_blk_n = res_stream_V_data_6_V_full_n;
    end else begin
        res_stream_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_6_V_write = 1'b1;
    end else begin
        res_stream_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_7_V_blk_n = res_stream_V_data_7_V_full_n;
    end else begin
        res_stream_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_7_V_write = 1'b1;
    end else begin
        res_stream_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_8_V_blk_n = res_stream_V_data_8_V_full_n;
    end else begin
        res_stream_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_8_V_write = 1'b1;
    end else begin
        res_stream_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        res_stream_V_data_9_V_blk_n = res_stream_V_data_9_V_full_n;
    end else begin
        res_stream_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_stream_V_data_9_V_write = 1'b1;
    end else begin
        res_stream_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_2234_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_2234_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((io_acc_block_signal_op1690 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((io_acc_block_signal_op843 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((io_acc_block_signal_op843 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (io_acc_block_signal_op843 == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start = grp_dense_wrapper_ap_fixed_ap_fixed_12_6_5_3_0_config11_s_fu_1828_ap_start_reg;

assign i_in_fu_2240_p2 = (ap_phi_mux_i_in_0_phi_fu_1820_p4 + 5'd1);

assign icmp_ln41_fu_2234_p2 = ((ap_phi_mux_i_in_0_phi_fu_1820_p4 == 5'd25) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op1690 = (res_stream_V_data_9_V_full_n & res_stream_V_data_8_V_full_n & res_stream_V_data_7_V_full_n & res_stream_V_data_6_V_full_n & res_stream_V_data_5_V_full_n & res_stream_V_data_4_V_full_n & res_stream_V_data_3_V_full_n & res_stream_V_data_2_V_full_n & res_stream_V_data_1_V_full_n & res_stream_V_data_0_V_full_n);

assign io_acc_block_signal_op843 = (data_stream_V_data_9_V_empty_n & data_stream_V_data_8_V_empty_n & data_stream_V_data_7_V_empty_n & data_stream_V_data_6_V_empty_n & data_stream_V_data_5_V_empty_n & data_stream_V_data_4_V_empty_n & data_stream_V_data_3_V_empty_n & data_stream_V_data_2_V_empty_n & data_stream_V_data_1_V_empty_n & data_stream_V_data_15_V_empty_n & data_stream_V_data_14_V_empty_n & data_stream_V_data_13_V_empty_n & data_stream_V_data_12_V_empty_n & data_stream_V_data_11_V_empty_n & data_stream_V_data_10_V_empty_n & data_stream_V_data_0_V_empty_n);

assign res_stream_V_data_0_V_din = tmp_data_0_V_reg_10359;

assign res_stream_V_data_1_V_din = tmp_data_1_V_reg_10364;

assign res_stream_V_data_2_V_din = tmp_data_2_V_reg_10369;

assign res_stream_V_data_3_V_din = tmp_data_3_V_reg_10374;

assign res_stream_V_data_4_V_din = tmp_data_4_V_reg_10379;

assign res_stream_V_data_5_V_din = tmp_data_5_V_reg_10384;

assign res_stream_V_data_6_V_din = tmp_data_6_V_reg_10389;

assign res_stream_V_data_7_V_din = tmp_data_7_V_reg_10394;

assign res_stream_V_data_8_V_din = tmp_data_8_V_reg_10399;

assign res_stream_V_data_9_V_din = tmp_data_9_V_reg_10404;

assign start_out = real_start;

endmodule //dense_array_array_ap_fixed_12_6_5_3_0_10u_config11_s
